import type { Duo } from './index';

export const DUO_P_F: Record<string, Record<string, Duo>> = {
  '/blog/': {
    articulos: [
      'El blog de trajes para bomberos reúne guías para especificar, normas y certificación, comparativas, vida útil y servicio, además de compras y licitación. Cada artículo parte de una decisión de operación: capas, tallas, alcance de protección, expediente o mantenimiento del equipo contra incendios.',
      'Usa las categorías para llegar a la duda que tienes en la requisición y compárala con la ficha técnica de cada partida. Si tu caso combina varias familias, <a href="/blog/como-elegir-traje-para-bomberos/">cómo elegir traje para bomberos</a> ayuda a ordenar la primera conversación antes de cotizar.',
    ],
    destacado: [
      'El artículo destacado del blog de trajes para bomberos explica cómo separar estructural, brigadista, forestal, aproximación, entrada y extricación antes de la primera compra. Esa elección define la exposición que cubrirá el equipo y evita comparar prendas que responden a riesgos distintos.',
      'Empieza con <a href="/blog/como-elegir-traje-para-bomberos/">cómo elegir traje para bomberos</a> si necesitas convertir una solicitud general en partidas concretas. Después podrás pedir tallas, composite, norma declarada y complementos compatibles sin mezclar el uniforme de estación con el EPP.',
    ],
  },
  '/blog/categoria/comparativas/': {
    articulos: [
      'Las comparativas entre familias de traje aclaran decisiones que una fotografía no resuelve: estructural frente a brigadista y uniforme de estación frente a traje de protección. Sirven a responsables de seguridad, compras y mandos que necesitan conectar el riesgo real con la partida correcta.',
      'Lee <a href="/blog/traje-estructural-o-brigadista/">traje estructural o traje de brigadista</a> antes de aceptar opciones que parecen equivalentes. La comparación por escenario, capas y alcance permite solicitar cotizaciones comparables y evita llevar equipo de conato a una operación de ataque interior.',
    ],
  },
  '/blog/categoria/especificacion/': {
    articulos: [
      'Cómo especificar equipo de bombero reúne criterios para botas, casco, ERA, trajes, Nomex IIIA, precio, TPP y THL. Los artículos traducen una necesidad operativa a campos verificables: material, ajuste, talla, alcance, composite y declaración normativa del modelo ofrecido.',
      'El punto de partida es <a href="/blog/como-elegir-traje-para-bomberos/">cómo elegir traje para bomberos</a>; después revisa la pieza que completa tu dotación. Lleva a la cotización el escenario, número de usuarios y configuración requerida para que cada partida pueda compararse por escrito.',
    ],
  },
  '/blog/categoria/licitacion/': {
    articulos: [
      'Los artículos de compras y licitación explican cómo convertir una necesidad de protección en un expediente defendible. Están dirigidos a áreas que deben separar partidas, solicitar fichas técnicas, pedir declaraciones de norma y evitar que una omisión documental altere la comparación entre ofertas.',
      'Consulta <a href="/blog/licitacion-trajes-bomberos-expediente/">licitación de trajes para bomberos</a> antes de cerrar el pliego. Te ayuda a ordenar la ficha por partida, las condiciones escritas y los documentos que conviene revisar durante la junta de aclaraciones.',
    ],
  },
  '/blog/categoria/mantenimiento/': {
    articulos: [
      'Vida útil y servicio del equipo aborda el cuidado que conserva o retira una prenda antes de que falle en operación. La categoría sirve a estaciones y responsables de EPP que necesitan distinguir inspección, lavado, contaminación, registro de condición y fecha de fabricación.',
      'Revisa <a href="/blog/vida-util-traje-bombero-nfpa-1850/">vida útil del traje de bombero</a> para ordenar la bitácora del conjunto estructural. Tener la fecha, inspecciones y acciones de servicio por pieza permite detectar un retiro antes de asumir que la prenda sigue disponible.',
    ],
  },
  '/blog/categoria/normas/': {
    articulos: [
      'Normas y certificación reúne explicaciones sobre NFPA 1970 y NOM-002-STPS-2010 aplicadas a una compra real. Está pensada para quien debe leer una referencia técnica, separar una obligación de un requisito de pliego y verificar qué declara el fabricante del modelo.',
      'Empieza por <a href="/blog/nfpa-1970-que-cambio/">NFPA 1970</a> si tu expediente cita varias normas anteriores. Después contrasta la referencia con la operación, porque una norma mencionada sin alcance, edición y evidencia del modelo no vuelve equivalente una oferta.',
    ],
  },
  '/blog/como-elegir-botas-de-bombero/': {
    relacionados: [
      'Cómo elegir botas de bombero se complementa con la selección del traje y del casco, porque la bota debe trabajar con el pantalón, el terreno y la salida prevista. Antes de requisitar, define si habrá agua, marcha prolongada, calor, lodo o intervención estructural.',
      'Lee <a href="/blog/como-elegir-traje-para-bomberos/">cómo elegir traje para bomberos</a> y <a href="/blog/como-elegir-casco-de-bombero/">cómo elegir casco de bombero</a> para cerrar el conjunto por operación. Escribe por WhatsApp el tipo de servicio, tallas y configuración de la dotación para recibir partidas comparables.',
    ],
  },
  '/blog/como-elegir-casco-de-bombero/': {
    relacionados: [
      'Cómo elegir casco de bombero gana contexto al revisarse junto con el ERA y la familia de traje: suspensión, barbiquejo, visor y nuca deben convivir con máscara, capucha y movimiento. La requisición debe describir la operación más exigente, no solo el color o la silueta.',
      'Continúa con <a href="/blog/como-elegir-equipo-de-respiracion-autonoma/">cómo elegir equipo de respiración autónoma</a> y <a href="/blog/como-elegir-traje-para-bomberos/">cómo elegir traje para bomberos</a>. Comparar esas interfaces antes de pedir evita que casco, máscara y protección de cuello lleguen como componentes aislados.',
    ],
  },
  '/blog/como-elegir-equipo-de-respiracion-autonoma/': {
    relacionados: [
      'Cómo elegir equipo de respiración autónoma se relaciona con el casco y el traje estructural porque máscara, regulador, capucha y arnés se prueban como sistema. Antes de cotizar, establece atmósfera, tiempo de trabajo, número de usuarios, recarga, inspección y almacenamiento.',
      'Complementa esta guía con <a href="/blog/como-elegir-casco-de-bombero/">cómo elegir casco de bombero</a> y <a href="/blog/tpp-y-thl-traje-estructural/">TPP y THL del traje estructural</a>. Comparar ambas lecturas ayuda a especificar protección respiratoria y térmica sin dar por compatible una configuración incompleta.',
    ],
  },
  '/blog/como-elegir-traje-para-bomberos/': {
    relacionados: [
      'Cómo elegir traje para bomberos abre la decisión de familia; después conviene profundizar en la diferencia entre un conjunto estructural y uno de brigada. Esa comparación separa ataque interior, conato, evacuación y primera respuesta antes de calcular tallas o accesorios.',
      'Sigue con <a href="/blog/traje-estructural-o-brigadista/">traje estructural o traje de brigadista</a> y <a href="/blog/cuanto-cuesta-un-traje-de-bombero/">cuánto cuesta un traje de bombero</a>. Con el escenario definido, escribe por WhatsApp la operación y cantidad para recibir una cotización organizada por partidas.',
    ],
  },
  '/blog/cuanto-cuesta-un-traje-de-bombero/': {
    relacionados: [
      'Cuánto cuesta un traje de bombero se entiende mejor después de definir la familia y los campos que cambian una cotización: composite, talla, norma declarada, cantidad y configuración. Sin ese alcance, dos ofertas pueden usar el mismo nombre para equipos de protección distintos.',
      'Consulta <a href="/blog/como-elegir-traje-para-bomberos/">cómo elegir traje para bomberos</a> y <a href="/blog/licitacion-trajes-bomberos-expediente/">licitación de trajes para bomberos</a> para preparar la comparación. Pide cada partida con su ficha técnica y condiciones por escrito antes de decidir por una cifra aislada.',
    ],
  },
  '/blog/licitacion-trajes-bomberos-expediente/': {
    relacionados: [
      'La licitación de trajes para bomberos necesita conectar el expediente con una especificación técnica verificable. La lectura sobre NFPA 1970 aclara cómo citar una referencia, mientras que la guía de precio ayuda a separar configuraciones distintas en partidas que sí pueden compararse.',
      'Revisa <a href="/blog/nfpa-1970-que-cambio/">NFPA 1970</a> y <a href="/blog/cuanto-cuesta-un-traje-de-bombero/">cuánto cuesta un traje de bombero</a> antes de redactar requisitos. Solicita por WhatsApp la ficha de cada partida, la norma declarada y documentación para licitación según tu operación.',
    ],
  },
  '/blog/nfpa-1970-que-cambio/': {
    relacionados: [
      'NFPA 1970 se lee junto con TPP y THL porque la referencia del conjunto estructural no sustituye los datos de desempeño del composite. También conviene revisar la vida útil: selección, etiqueta, mantenimiento y retiro forman parte de la disponibilidad del equipo.',
      'Continúa con <a href="/blog/tpp-y-thl-traje-estructural/">TPP y THL del traje estructural</a> y <a href="/blog/vida-util-traje-bombero-nfpa-1850/">vida útil del traje de bombero</a>. Lleva al pliego la edición requerida y pide evidencia del estatus que el fabricante declara para el modelo.',
    ],
  },
  '/blog/nom-002-stps-2010-equipo-para-brigadas/': {
    relacionados: [
      'NOM-002-STPS-2010 se complementa con la comparación entre brigadista y estructural: dotar EPP a una brigada no significa enviar un conjunto de conato a ataque interior. El análisis de riesgo y la función de la brigada determinan qué protección se solicita.',
      'Lee <a href="/blog/traje-estructural-o-brigadista/">traje estructural o traje de brigadista</a> y <a href="/blog/como-elegir-traje-para-bomberos/">cómo elegir traje para bomberos</a> antes de armar la requisición. Indica por WhatsApp tareas, usuarios y exposición para separar las partidas necesarias con alcance claro.',
    ],
  },
  '/blog/nomex-iiia-que-es/': {
    relacionados: [
      'Nomex IIIA es solo una parte de la conversación sobre materiales; para un traje estructural importan las capas completas y el comportamiento térmico del composite. Comparar por el nombre de una fibra sin conocer barrera, forro y uso puede ocultar diferencias relevantes.',
      'Sigue con <a href="/blog/tpp-y-thl-traje-estructural/">TPP y THL del traje estructural</a> y <a href="/blog/como-elegir-traje-para-bomberos/">cómo elegir traje para bomberos</a>. Pide la composición por capa y la aplicación prevista para que la tela no se convierta en el único criterio.',
    ],
  },
  '/blog/tpp-y-thl-traje-estructural/': {
    relacionados: [
      'TPP y THL del traje estructural deben leerse con la selección de familia y con la vida útil del conjunto. Los dos valores pertenecen al composite terminado; no describen por separado una tela ni sustituyen talla, barrera de humedad, inspección o retiro por condición.',
      'Consulta <a href="/blog/nomex-iiia-que-es/">Nomex IIIA</a> para distinguir fibra y sistema, además de <a href="/blog/vida-util-traje-bombero-nfpa-1850/">vida útil del traje de bombero</a>. Pide esos datos completos en la ficha antes de comparar ofertas estructurales por una sola cifra.',
    ],
  },
  '/blog/traje-estructural-o-brigadista/': {
    relacionados: [
      'Traje estructural o traje de brigadista es la comparación central antes de revisar requisitos de NOM-002-STPS-2010 y presupuesto. Define si la gente controla un conato, evacúa o entra a un incendio, porque el escenario cambia construcción, equipo complementario y alcance de protección.',
      'Lee <a href="/blog/nom-002-stps-2010-equipo-para-brigadas/">NOM-002-STPS-2010</a> y <a href="/blog/cuanto-cuesta-un-traje-de-bombero/">cuánto cuesta un traje de bombero</a> para documentar la decisión. Escribe por WhatsApp qué tareas realiza tu brigada y recibe partidas alineadas con esa exposición real de trabajo cotidiano.',
    ],
  },
  '/blog/uniforme-de-bombero-que-incluye/': {
    relacionados: [
      'Uniforme de bombero se conecta con la elección de familia porque ropa de estación y EPP cumplen funciones distintas. Revisar traje estructural o brigadista aclara cuándo una prenda identifica al personal y cuándo se requiere una barrera para conato, fuego o rescate.',
      'Continúa con <a href="/blog/traje-estructural-o-brigadista/">traje estructural o traje de brigadista</a> y <a href="/blog/como-elegir-traje-para-bomberos/">cómo elegir traje para bomberos</a>. Antes de pedir, lista por separado uniforme, protección por riesgo, tallas y complementos necesarios para cada usuario de la dotación.',
    ],
  },
  '/blog/vida-util-traje-bombero-nfpa-1850/': {
    relacionados: [
      'La vida útil del traje de bombero depende de seleccionar el conjunto correcto, leer su etiqueta y registrar inspecciones, lavados y condición. NFPA 1970 aporta el contexto del producto estructural; NFPA 1850 ordena el cuidado y retiro desde la fecha de fabricación.',
      'Revisa <a href="/blog/nfpa-1970-que-cambio/">NFPA 1970</a> y <a href="/blog/tpp-y-thl-traje-estructural/">TPP y THL del traje estructural</a> para completar la evaluación. Al recibir una partida, anota fecha y configuración de cada pieza antes de ponerla formalmente en servicio operativo.',
    ],
  },
  '/trajes/extricacion/': {
    completa: [
      'El traje de extricación para rescate vehicular funciona con casco, guantes, botas y, cuando la atmósfera lo exige, ERA seleccionados para la maniobra. La compatibilidad se revisa en movimiento: rodillas sobre asfalto, protección ocular, agarre de herramienta y visibilidad en carretera.',
      'Integra los complementos con el mismo escenario de extricación, no como compras aisladas. Revisa <a href="/cascos/">cascos para bombero</a> y <a href="/guantes/">guantes para bombero</a> al preparar la cotización; describe operación nocturna, riesgo biológico y tallas para cerrar un conjunto coherente.',
    ],
  },
  '/trajes/extricacion/chaqueta/': {
    aplicaciones: ['La chaqueta de rescate técnico se usa en extricación vehicular, rescate técnico en estructuras colapsadas y apoyo prehospitalario con exposición biológica. La especifican mandos de rescate que necesitan movilidad, codos reforzados y visibilidad sin cargar el chaquetón estructural en cada salida.', 'Describe en la solicitud si habrá trabajo dentro del habitáculo, junto a lámina o en carretera nocturna. Así se define talla sobre uniforme, cinta reflejante y el nivel requerido; pide por WhatsApp la configuración antes de convertir una chaqueta de trabajo en una partida de rescate.'],
    comparativa: ['La chaqueta de rescate técnico conviene ante vidrio, aceite y fluidos; el chaquetón estructural corresponde al riesgo térmico de ataque interior. La diferencia decisiva es el escenario, no la apariencia: una es monocapa con barrera biológica y la otra integra tres capas para fuego.', 'Reserva el chaquetón para incendio y especifica la chaqueta con corte, punción, patógenos y visibilidad para rescate. <a href="/trajes/estructural/">Trajes estructurales</a> ayuda a separar ambas partidas; solicita por escrito el nivel de certificación que exige tu operación.'],
    errores: ['Comprar una chaqueta de rescate técnico sin declarar el nivel de certificación puede entregar una protección que no corresponde a la maniobra. Otro error es salir a choques con el chaquetón estructural: aceite y fluidos contaminan un equipo que no fue seleccionado para ese trabajo.', 'Evita ambos problemas describiendo rescate vehicular, exposición biológica y trabajo nocturno en la cotización. Pide la ficha de la chaqueta con su nivel declarado, cinta reflejante y refuerzos de codo; la partida queda verificable antes de firmar.'],
    faq: ['Las dudas sobre chaqueta de rescate técnico aclaran si protege frente a fuego, qué significan sus dos niveles y cómo se descontamina después de fluidos. También distinguen esta prenda de una chamarra de trabajo y explican por qué se coloca sobre el uniforme de estación.', 'Escríbenos por WhatsApp si necesitas definir nivel, talla de pecho y manga, o la salida que cubrirá. Indica si hay extricación, mando de incidente o atención prehospitalaria para recibir la información útil de la chaqueta de rescate técnico.'],
    ficha: ['La especificación de la chaqueta de rescate técnico debe copiar NFPA 1950 edición 2025 como referencia, nivel declarado, construcción monocapa y barrera contra patógenos. Añade resistencia a corte y punción, refuerzos de codo y antebrazo, cinta reflejante, talla por pecho y largo de manga.', 'Pide la ficha técnica por escrito con esos campos y la tela exterior propuesta. Así el anexo separa una prenda de rescate de un chaquetón estructural y permite comparar configuraciones antes de liberar la requisición.'],
    hermanas: ['La chaqueta de rescate técnico se combina con pantalón de rescate, conjunto de dos piezas, overol, conjunto dual y pantalón de cubierta. Cada formato responde a vestido, desgaste y alcance distintos dentro de extricación y rescate.', 'Puedes comprar la chaqueta por pieza para reposición o armar una dotación completa desde <a href="/trajes/extricacion/">extricación y rescate</a>. Define cuáles usuarios trabajan hincados, cuáles requieren cobertura rápida y qué complementos acompañarán cada conjunto.'],
    incluye: ['La chaqueta de rescate técnico incluye construcción monocapa con refuerzos en codos y antebrazos, cinta reflejante de alta visibilidad y ficha con nivel de certificación declarado. El pantalón de rescate, guantes de extricación, casco y goggles se cotizan por separado.', 'Separa el alcance en cada oferta para que una chaqueta no parezca una dotación completa. Solicita la misma lista de incluidos y excluidos por partida, y agrega los complementos compatibles cuando la operación requiera protección ocular, agarre o calzado.'],
    relacionados: ['Junto con la chaqueta de rescate técnico conviene revisar el pantalón que recibe el desgaste de rodilla y el conjunto cuando se necesita que ambas piezas compartan corte y nivel. Esas decisiones evitan una interfaz improvisada para rescate vehicular.', 'Consulta <a href="/trajes/extricacion/pantalon/">pantalón de rescate técnico</a> y <a href="/trajes/extricacion/conjunto/">conjunto de extricación</a> antes de cerrar la requisición. Anota usuarios, tallas y tipo de salida para decidir si conviene reposición por pieza, set completo o combinación operativa de turno.'],
  },
  '/trajes/extricacion/pantalon/': {
    aplicaciones: ['El pantalón de rescate técnico trabaja en extricación vehicular, rescate en estructuras y atención prehospitalaria; su rodilla acolchada y reforzada responde a vidrio, lámina y asfalto. Lo especifica quien necesita proteger al usuario hincado sin vestir una pantalonera estructural para cada llamado.', 'Indica en la cotización si habrá trabajo dentro del vehículo, carretera nocturna o contacto biológico. Con esos datos se definen cintura, largo, cinta reflejante y nivel requerido; pide la ficha de la prenda antes de asignarla a la dotación.'],
    comparativa: ['El pantalón de rescate técnico sirve para corte, punción y exposición biológica durante extricación; la pantalonera estructural está diseñada para protección térmica. El dato que define la compra es el riesgo dominante: trabajar hincado sobre lámina no equivale a entrar a un incendio.', 'Pide rodilla acolchada y reforzada, barrera declarada y cinta en pierna para rescate. Para la partida de fuego consulta <a href="/trajes/estructural/">trajes estructurales</a>; mantener ambos usos separados conserva disponibilidad de cada equipo y aclara la requisición.'],
    errores: ['Un pantalón de rescate técnico con solo refuerzo puede resistir abrasión pero resultar insoportable durante una maniobra hincada; sin acolchado falta una función esencial. Ignorar la cinta en pierna también reduce visibilidad cuando el usuario trabaja junto al vehículo.', 'Evita comparar fotografías: pide la ficha con acolchado, refuerzo, resistencia mecánica y cinta reflejante. Revisa la rodilla tras cada salida y declara el nivel de certificación en la orden para no recibir una configuración sin el alcance requerido.'],
    faq: ['Las preguntas del pantalón de rescate técnico explican por qué rodilla acolchada y refuerzo no son lo mismo, cómo se descontamina tras fluidos y qué revisar después de cada salida. También aclaran por qué no conviene sustituirlo con pantalonera estructural.', 'Manda por WhatsApp cintura, largo, uniforme que irá debajo y tipo de rescate. Con esos datos se puede orientar la talla, el nivel declarado y la necesidad de compra por pieza para reposición de la zona que más desgaste recibe.'],
    ficha: ['Para especificar pantalón de rescate técnico anota NFPA 1950 edición 2025 como referencia, nivel declarado, barrera contra patógenos, construcción monocapa y resistencia a corte y punción. La rodilla debe figurar acolchada y reforzada; agrega cinta en pierna, cintura, largo y cierre.', 'Pide la ficha técnica por escrito y transcribe los campos al anexo de compra. Esa precisión diferencia el pantalón de una pantalonera estructural y permite validar que la prenda seleccionada acompaña el trabajo hincado sobre vidrio y lámina.'],
    hermanas: ['El pantalón de rescate técnico comparte familia con chaqueta, conjunto, overol, conjunto dual y pantalón de cubierta. La pieza inferior se repone con frecuencia por el contacto de rodilla, mientras que los demás formatos cambian velocidad de vestido y cobertura.', 'Cotiza el pantalón suelto cuando necesitas reponer desgaste o integra una dotación desde <a href="/trajes/extricacion/">extricación y rescate</a>. Define el formato por usuario y operación para que la misma familia no se convierta en una compra genérica.'],
    incluye: ['El pantalón de rescate técnico incluye prenda monocapa con rodilla acolchada y reforzada, cinta reflejante en pierna y ficha con nivel de certificación. Chaqueta, cinturón y rodilleras exteriores independientes no forman parte de esta partida.', 'Pide que incluidos y excluidos aparezcan separados en cada propuesta. Así la comparación conserva el mismo alcance y puedes sumar chaqueta, guantes, botas o accesorios cuando la operación requiera cerrar el conjunto de rescate.'],
    relacionados: ['El pantalón de rescate técnico se revisa con la chaqueta que completa el sistema y con el conjunto de extricación si se busca mismo corte y nivel. También permite contrastar su rodilla mecánica con la pantalonera destinada al riesgo térmico.', 'Abre <a href="/trajes/extricacion/chaqueta/">chaqueta de rescate técnico</a> y <a href="/trajes/extricacion/conjunto/">conjunto de extricación</a> antes de solicitar precios. Define si buscas reposición, dotación inicial o una combinación por usuario, talla, turno, tipo de intervención y condiciones de uso.'],
  },
  '/trajes/extricacion/conjunto/': {
    aplicaciones: ['El conjunto de extricación responde a dotación inicial de rescate, accidentes viales, colapsos y apoyo en escena. Chaqueta y pantalón del mismo corte protegen al usuario frente a corte, punción y exposición biológica sin consumir el conjunto estructural en salidas que no son incendio.', 'Especifica cuántos elementos salen a rescate por turno y qué uniforme usarán debajo. Ese dato permite pedir tallas por persona, mismo nivel en ambas piezas y cinta reflejante para carretera, en lugar de armar pares de modelos distintos.'],
    comparativa: ['El conjunto de extricación de dos piezas conviene cuando el desgaste obliga a reemplazar solo pantalón o chaqueta; el overol gana cuando el vestido inmediato y la cobertura continua pesan más. La elección se define por frecuencia de rescate, desgaste de rodilla y tiempo de salida.', 'Compara reposición, interfaz de cintura y velocidad antes de seleccionar formato. <a href="/trajes/extricacion/overol/">Overol de rescate técnico</a> muestra la alternativa de una pieza; solicita por escrito corte, nivel y tallas de la dotación que realmente usará cada elemento.'],
    errores: ['Mezclar un conjunto de extricación con piezas de modelos distintos deja cintura, tela o nivel sin correspondencia. Guardarlo después de una salida con fluidos sin descontaminación también conserva un riesgo biológico que no siempre se aprecia a simple vista.', 'Pide ambas prendas como sistema, con nivel declarado y talla por elemento. Incluye en el procedimiento qué salidas activan este conjunto y cuándo se limpia; así la compra evita que el equipo estructural siga siendo la respuesta improvisada ante cada choque.'],
    faq: ['Las dudas del conjunto de extricación resuelven si conviene comprar por pieza, cómo definir cuándo se usa y por qué las dos prendas deben compartir nivel. También explican su vestido sobre uniforme y el procedimiento distinto para suciedad mecánica o contacto con fluidos.', 'Escríbenos por WhatsApp el número de rescatistas, sus tallas y las salidas habituales. Esa información ayuda a decidir si la primera compra debe ser set completo y qué reposiciones se prevén por rodilla, contaminación o condición.'],
    ficha: ['La ficha del conjunto de extricación debe indicar NFPA 1950 edición 2025 como referencia, dos niveles según fabricante y barrera contra patógenos. Copia además formato de dos piezas, construcción monocapa, interfaz diseñada como sistema, refuerzos en codos, antebrazos y rodillas, más tallas por elemento.', 'Solicita esa ficha por escrito para que chaqueta y pantalón se evalúen como una sola configuración. El anexo técnico debe incluir tela exterior, cinta reflejante y nivel común antes de comparar una oferta contra otra.'],
    hermanas: ['El conjunto de extricación convive con chaqueta y pantalón por separado, overol de vestido rápido, conjunto dual para rescate y forestal, y pantalón de cubierta. Las piezas hermanas permiten ajustar la dotación al desgaste, la urgencia y el alcance de cada salida.', 'Revisa la familia <a href="/trajes/extricacion/">extricación y rescate</a> si necesitas combinar formatos. Compra el set para una primera dotación o piezas sueltas para reposición, siempre con talla, función, turno y operación documentados por usuario.'],
    incluye: ['El conjunto de extricación incluye chaqueta y pantalón del mismo corte y nivel, refuerzos en codos, antebrazos y rodillas, además de cinta reflejante en ambas prendas. Guantes, casco, goggles y botas se cotizan como complementos separados.', 'Solicita que el alcance se enumere de esa forma en cada cotización. Así puedes incorporar los complementos compatibles sin atribuirlos al set y comparar dos propuestas que cubren exactamente las mismas dos piezas.'],
    relacionados: ['Antes de contratar un conjunto de extricación conviene revisar la chaqueta para reposición individual y el overol para estaciones donde la salida requiere vestido inmediato. Son decisiones de formato que influyen en la disponibilidad de la dotación durante el turno.', 'Consulta <a href="/trajes/extricacion/chaqueta/">chaqueta de rescate técnico</a> y <a href="/trajes/extricacion/overol/">overol de rescate técnico</a>. Define en la requisición frecuencia de uso, desgaste esperado, tallas y tiempo de respuesta antes de elegir entre dos piezas o una sola.'],
  },
  '/trajes/extricacion/overol/': {
    aplicaciones: ['El overol de rescate técnico se usa en salidas súbitas, extricación vehicular, apoyo prehospitalario y cuerpos rurales con doble uso cuando el modelo lo declara. Su una pieza cubre la cintura y se coloca rápido sobre el uniforme para trabajar en un habitáculo.', 'Describe si el usuario debe vestirlo con botas puestas, entrar a vehículos o cubrir rescate y forestal. Con esa información se define cierre frontal, talla por estatura y torso, y si se requiere doble certificación declarada en la etiqueta.'],
    comparativa: ['El overol de rescate técnico favorece velocidad de vestido y cobertura continua; el conjunto de dos piezas favorece cambiar solo la prenda dañada. El desgaste de rodilla y la necesidad de abrir la prenda completa durante el turno son datos prácticos que resuelven la comparación.', 'Elige una pieza cuando la salida inmediata es prioritaria y dos piezas si anticipas reposición frecuente. <a href="/trajes/extricacion/conjunto/">Conjunto de extricación</a> permite contrastar esa logística; pide tallas reales y confirma que el cierre funciona con la bota de servicio.'],
    errores: ['Elegir un overol de rescate técnico por talla estimada puede dejar el torso corto y limitar brazos al agacharse. Otro error es asumir doble certificación: solo algunos modelos la tienen y debe declararse en etiqueta, no inferirse del formato.', 'Evita la improvisación midiendo estatura y torso con el uniforme de trabajo. Solicita la ficha que confirme cierre, nivel, barrera y estatus declarado del modelo; si habrá uso rural, agrega expresamente la necesidad de rescate y forestal.'],
    faq: ['Las preguntas del overol de rescate técnico abordan su diferencia frente al conjunto, el uso con botas puestas, la talla de torso y la descontaminación después de fluidos. También aclaran que la protección frente a incendio interior no se presume por ser una prenda completa.', 'Comparte por WhatsApp estaturas, tipo de bota y tiempo de respuesta de la estación. Con esos datos se orienta el formato, la talla y si la configuración debe ser simple o dual para las salidas que atiende la unidad.'],
    ficha: ['Especifica el overol de rescate técnico con NFPA 1950 edición 2025 como referencia, barrera contra patógenos, construcción monocapa y formato de una pieza. Añade cierre frontal de vestido rápido, refuerzos en rodillas y codos, talla por estatura y torso, cinta reflejante y certificación simple o dual.', 'Pide la ficha técnica por escrito y confirma la condición de doble certificación solo si el modelo la declara. Esa lista impide que una prenda de rapidez se cotice sin resolver talla, cierre ni alcance operativo.'],
    hermanas: ['El overol de rescate técnico comparte familia con conjunto de dos piezas, chaqueta, pantalón, conjunto dual y pantalón de cubierta. Su diferencia es eliminar la cintura y acelerar el vestido, mientras que las otras piezas permiten reposición localizada o cobertura parcial.', 'Explora <a href="/trajes/extricacion/">extricación y rescate</a> para elegir por servicio. Compra el overol por pieza o combina formatos según la unidad, pero asigna talla individual para que la rapidez de colocación no se pierda en una prenda compartida.'],
    incluye: ['El overol de rescate técnico incluye una pieza con refuerzos en rodillas y codos, cierre frontal de vestido rápido y cinta reflejante. Guantes de extricación, casco, goggles y botas no vienen dentro de la partida y requieren cotización por separado.', 'Pide que la propuesta liste el overol y sus exclusiones sin agrupar accesorios. Así puedes comprobar que el cierre, la talla y los refuerzos corresponden al modelo elegido, además de agregar los complementos necesarios para la operación.'],
    relacionados: ['El overol de rescate técnico se revisa junto con el conjunto de extricación, que cambia la lógica de reposición, y con el conjunto dual cuando una unidad también combate vegetación. Ambos enlaces ayudan a definir si rapidez, servicio o doble escenario controla la compra.', 'Consulta <a href="/trajes/extricacion/conjunto/">conjunto de extricación</a> y <a href="/trajes/extricacion/conjunto-dual/">conjunto dual rescate y forestal</a>. Envía la lista de salidas de la estación para comparar formatos sobre el mismo riesgo, talla, desgaste, disponibilidad, personal asignado y tiempo operativo.'],
  },
  '/trajes/extricacion/conjunto-dual/': {
    aplicaciones: ['El conjunto dual rescate y forestal responde a cuerpos municipales, protección civil estatal y brigadas rurales que atienden accidentes viales e incendios de vegetación con la misma dotación. Combina requisitos de rescate técnico y forestal en una prenda monocapa para dos escenarios distintos.', 'Describe volumen de salidas, terreno, contacto biológico y trabajo nocturno al especificarlo. Esa información permite decidir formato, tallas, cinta reflejante y la declaración de ambas referencias, en vez de comprar una prenda forestal simple para una operación que también exige rescate.'],
    comparativa: ['El conjunto dual rescate y forestal conviene cuando una misma corporación cubre ambos escenarios con presupuesto para una dotación; dos equipos separados permiten optimizar cada uso. La decisión depende de volumen por servicio, logística de lavado y necesidad de especialización por operación.', 'Compara una etiqueta con ambas declaraciones, no solo el precio de una prenda forestal. Si las dos tareas son intensas, dos dotaciones pueden resolver mejor; si se alternan con la misma gente, pide por escrito composición, formato y alcance dual.'],
    errores: ['Aceptar un conjunto dual rescate y forestal solo de palabra deja sin evidencia la doble declaración que debe constar en etiqueta. También es incorrecto usarlo en incendio estructural: su construcción monocapa no incorpora barrera térmica ni de humedad para ataque interior.', 'Evita esos errores solicitando foto o información de etiqueta, referencias de rescate y forestal, además del procedimiento de lavado para cada salida. <a href="/trajes/estructural/">Trajes estructurales</a> cubren otra exposición y deben permanecer como partida independiente.'],
    faq: ['Las preguntas del conjunto dual rescate y forestal explican qué respalda la doble certificación, cuándo puede sustituir dos dotaciones y por qué se aplican procedimientos de lavado distintos tras vegetación o fluidos. También aclaran que no corresponde a incendio estructural.', 'Escribe por WhatsApp si la unidad alterna carretera y vegetación, cuántos usuarios participan y si existe criterio ambiental sin PFAS. Con esos datos se puede pedir la configuración dual adecuada y documentar la declaración requerida para la compra.'],
    ficha: ['La ficha del conjunto dual rescate y forestal debe consignar NFPA 1950 para rescate y para forestal, con declaración en etiqueta y estatus de referencia técnica voluntaria en México. Copia construcción monocapa, tela ignífuga inherente transpirable, refuerzos, formato, tallas y cinta reflejante.', 'Pide la ficha técnica por escrito y no llames certificado a un modelo sin esa declaración. Si se requiere opción sin PFAS o barrera biológica según modelo, inclúyelo en el anexo para que la propuesta sea evaluable.'],
    hermanas: ['El conjunto dual rescate y forestal comparte familia con conjunto dedicado, overol, chaqueta, pantalón y pantalón de cubierta. Sus hermanas cubren rescate de manera específica, mientras el dual reúne dos escenarios para una dotación con la misma gente.', 'Compara las alternativas desde <a href="/trajes/extricacion/">extricación y rescate</a> antes de comprar. Elige conjunto completo si predomina rescate, dual si alternas vegetación y carretera, y piezas sueltas cuando la reposición es el objetivo principal de la partida.'],
    incluye: ['El conjunto dual rescate y forestal incluye chaqueta y pantalón, u overol según configuración, con doble declaración solicitada, refuerzos en zonas de contacto y cinta reflejante. Casco, guantes, goggles, botas y ERA se cotizan fuera de esta partida.', 'Pide que el formato y la declaración aparezcan junto a los incluidos. Separar cada complemento permite verificar la dotación sin convertir una prenda dual en un conjunto de protección completo que no contempla respiración, cabeza ni calzado.'],
    relacionados: ['Al revisar conjunto dual rescate y forestal conviene contrastarlo con el conjunto de extricación dedicado y con el formato forestal equivalente. Esos destinos aclaran qué se gana al cubrir dos operaciones y qué se conserva cuando cada una tiene dotación propia.', 'Consulta <a href="/trajes/extricacion/conjunto/">conjunto de extricación</a> y <a href="/trajes/forestal/conjunto-dual/">conjunto dual forestal</a>. Solicita ambas configuraciones cuando la decisión dependa de frecuencia de salidas, presupuesto, mantenimiento, disponibilidad por turno, personal asignado, almacenamiento disponible y protocolos internos de servicio.'],
  },
  '/trajes/extricacion/cover-pants/': {
    aplicaciones: ['El pantalón de cubierta para rescate se usa en apoyos, derrames, atención médica y llamados menores donde se necesita proteger el uniforme sin vestir equipo completo. Lo especifica quien requiere calzarlo sobre ropa y botas en segundos para trabajo de contacto y vía pública.', 'Describe si el llamado implica solo suciedad y abrasión o una maniobra con vidrio y lámina. Esa diferencia fija el alcance: pide holgura, cierre rápido y cinta en pierna para cobertura ligera, o selecciona pantalón de extricación cuando el riesgo mecánico aumenta.'],
    comparativa: ['El pantalón de cubierta para rescate protege la ropa de trabajo y se calza con máxima rapidez; el pantalón de extricación se destina a maniobra pesada con corte y punción. La decisión se define por exposición mecánica, no por que ambas prendas se usen sobre uniforme.', 'Para apoyos y llamados menores solicita corte amplio, cierre de vestido rápido y talla con bota. Para extricación real revisa <a href="/trajes/extricacion/pantalon/">pantalón de rescate técnico</a>; pedir la referencia del modelo evita asumir que todos los pantalones de cubierta tienen certificación.'],
    errores: ['Usar pantalón de cubierta para rescate como sustituto de un pantalón de extricación expone al usuario ante vidrio y lámina. También es un error suponer certificación: varía por modelo y debe verificarse en ficha antes de incluirla en una requisición.', 'Evita ambas confusiones describiendo si la salida es apoyo ligero o rescate técnico. Pide alcance, modelo, holgura sobre uniforme y cierre compatible con bota; si la prenda se perfora o pierde función, programa su reposición en vez de improvisar una reparación.'],
    faq: ['Las preguntas del pantalón de cubierta para rescate aclaran para qué llamados sirve, si se coloca con bota puesta y por qué no reemplaza equipo certificado de extricación. También explican su vida de servicio como prenda de desgaste y la utilidad de guardarlo en la unidad.', 'Manda por WhatsApp tipo de apoyo, talla sobre uniforme y bota habitual. Esa información permite definir corte, largo y alcance del pantalón de cubierta para rescate, sin adjudicarle una protección mecánica que no declara el modelo.'],
    ficha: ['La especificación del pantalón de cubierta para rescate debe indicar referencia según modelo, alcance para proteger ropa de trabajo y estatus técnico voluntario. Añade construcción monocapa, corte amplio, cierre rápido, cinta en pierna, talla por cintura y largo con holgura, además de certificación solo si se verifica.', 'Pide la ficha técnica por escrito para conservar claro que no sustituye una prenda de maniobra pesada. La lista facilita comparar cierres, acceso con bota y configuración antes de asignarlo a una unidad de respuesta.'],
    hermanas: ['El pantalón de cubierta para rescate es la opción ligera frente a pantalón técnico, chaqueta, conjunto, overol y conjunto dual. Sus piezas hermanas cubren extricación con diferentes niveles de protección, velocidad y reposición; esta prenda cubre el espacio de apoyos cotidianos.', 'Revisa <a href="/trajes/extricacion/">extricación y rescate</a> para distribuir cada formato por salida. Compra cubierta para la unidad y pantalón técnico para maniobra pesada, siempre documentando qué riesgo, usuario y turno activa una u otra prenda.'],
    incluye: ['El pantalón de cubierta para rescate incluye prenda con cierre de vestido rápido y cinta reflejante en pierna. Chaqueta de rescate, pantalón de extricación certificado y botas no están incluidos, porque cubren funciones diferentes dentro de la dotación.', 'Exige que cada exclusión aparezca en la cotización. Así puedes comparar un pantalón ligero con otro de igual alcance y agregar por separado las piezas que sí necesita el personal para la extricación o protección de pie.'],
    relacionados: ['El pantalón de cubierta para rescate se contrasta con pantalón técnico para definir cuándo hay protección de prenda y cuándo se requiere resistencia de maniobra. El conjunto de extricación completa la revisión cuando el apoyo puede escalar a trabajo con vehículo, vidrio o lámina.', 'Consulta <a href="/trajes/extricacion/pantalon/">pantalón de rescate técnico</a> y <a href="/trajes/extricacion/conjunto/">conjunto de extricación</a>. Lleva una lista de llamados de la unidad para dividir cobertura ligera, rescate técnico, reposición y asignación por turno en partidas compatibles claramente separadas.'],
  },
};
