// ============================================================
// METAS SEO por ruta — tanda de metas página por página (2026-09-29).
// Title sin marca, sin «México» y sin «|»; description 135–158 con CTA;
// keywords de Ahrefs MX (web). Tiene prioridad sobre title/description
// de los datos del catálogo (secciones, tipos y modelos de complementos).
// Bitácora: OBSIDIAN/TRAJESBOMBERO/15-Metas-y-SEO-pagina-por-pagina.
// ============================================================
export interface MetaSeo {
  title: string;
  description: string;
  h1?: string;
  lead?: string;                         // lead del hero con la keyword principal
  faqsExtra?: { q: string; a: string }[]; // preguntas de la SERP (Ahrefs) que se anteponen a las FAQ
}

export const METAS_SEO: Record<string, MetaSeo> = {
  "/cascos/casco-estructural-tradicional/": {"title": "Casco estructural tradicional para bombero estilo americano", "description": "Casco estructural tradicional para bombero: componentes, norma de referencia, compatibilidad con ERA y qué pedir al cotizar un casco de ataque interior."},
  "/cascos/casco-estructural-europeo/": {"title": "Casco estructural europeo tipo jet para bombero EN 443", "description": "Casco estructural europeo tipo jet: cobertura, visor integrado, compatibilidad con ERA y referencia EN 443:2008 para evaluar una cotización de bomberos."},
  "/cascos/casco-forestal/": {"title": "Casco forestal para bombero ligero y de ala completa", "description": "Casco forestal para bombero: peso, ala completa, ventilación, clips para goggles y norma de referencia para trabajo prolongado en línea de fuego. Cotiza."},
  "/cascos/casco-rescate-tecnico/": {"title": "Casco de rescate técnico para bombero y rescate vertical", "description": "Casco de rescate técnico: perfil compacto, retención de cuatro puntos y lámpara para rescate vehicular, vertical y espacios confinados. Cotiza con ficha."},
  "/cascos/casco-brigada-industrial/": {"title": "Casco para brigada industrial contra incendio", "description": "Casco para brigada industrial contra incendio: cuándo basta un casco industrial y cuándo el riesgo exige casco estructural para combate interior. Cotiza."},
  "/cascos/bullard-ltx/": {"title": "Casco Bullard LTX estructural con visor y ratchet", "description": "Casco Bullard LTX estructural con visor, ajuste ratchet y suspensión de seis puntos. Revisa la configuración y cotiza con ficha técnica.", "h1": "Casco Bullard LTX estructural con visor", "lead": "El casco Bullard LTX usa carcasa de termoplástico de alto impacto, ajuste ratchet y suspensión de seis puntos. Confirma color, visor y compatibilidad con tu ERA antes de cotizar.", "faqsExtra": [{"q": "¿Qué protege un casco Bullard LTX?", "a": "El LTX está publicado como casco estructural para combate de incendios. Su ficha declara carcasa de termoplástico de alto impacto, cubrenuca de Nomex y visor de policarbonato. La protección efectiva depende de que se use con el conjunto compatible, incluyendo máscara de ERA, capucha y barbiquejo ajustado."}, {"q": "¿Cómo se ajusta el casco Bullard LTX?", "a": "El modelo declara ajuste ratchet y suspensión de seis puntos. La prueba se hace con máscara, capucha y chaquetón puestos. Ajusta la perilla y revisa que el casco no gire al mirar hacia arriba. Si el visor desplaza la máscara, corrige la configuración antes de asignarlo."}]},
  "/cascos/bullard-ust-lw/": {"title": "Casco Bullard UST LW ultraligero con visor ReTrack", "description": "Casco Bullard UST LW ultraligero de fibra de vidrio, con ajuste Sure-Lock y visor ReTrack. Define la protección ocular y cotiza con ficha técnica.", "h1": "Casco Bullard UST LW ultraligero con ReTrack", "lead": "El casco Bullard UST LW es un modelo estructural de estilo Nueva York con fibra de vidrio, ajuste Sure-Lock y visor ReTrack. Define la protección ocular antes de cotizar.", "faqsExtra": [{"q": "¿Qué distingue al casco Bullard UST LW?", "a": "El UST LW se diferencia por su estilo Nueva York ultraligero, carcasa de fibra de vidrio y ajuste Sure-Lock. Su ficha declara menos de 1.54 kg con visor ReTrack. No comparte la carcasa termoplástica ni el visor de cuatro pulgadas del LTX, por lo que conviene probar ambos con el ERA."}, {"q": "¿Qué protección ocular puede llevar el Bullard UST LW?", "a": "La ficha del UST LW declara visor integrado ReTrack y opción de careta o goggles. Cada alternativa cambia la configuración y el peso publicado. Define la opción antes de pedir cotización y pruébala con la máscara de ERA para comprobar que no interfiera con el campo de visión."}]},
  "/cascos/bullard-fh911h/": {"title": "Casco forestal Bullard Wildland FH911H para bombero", "description": "Casco forestal Bullard Wildland FH911H: suspensión de seis puntos y clips para goggles, ligero para línea de fuego. Cotiza con ficha técnica y configuración.", "h1": "Casco forestal Bullard Wildland FH911H"},
  "/cascos/skold-viking/": {"title": "Casco de bombero Sköld Viking FPCM con protector facial", "description": "Casco de bombero Sköld Viking FPCM estructural: ajuste de matraca, barbiquejo de cuatro puntos y protector facial. Cotiza con ficha técnica y configuración."},
  "/equipo-de-respiracion-autonoma/era-de-combate/": {"title": "ERA para combate de incendios con PASS y alarmas", "description": "ERA para combate de incendios: autonomía nominal, PASS, alarmas, máscara y referencia NFPA 1970 para revisar una cotización institucional de bomberos."},
  "/equipo-de-respiracion-autonoma/cilindros-de-fibra-de-carbono/": {"title": "Cilindros de fibra de carbono para ERA de 4,500 psi", "description": "Cilindros de fibra de carbono para ERA: 4,500 psi, duración nominal, etiqueta DOT, válvula, conexión y prueba hidrostática. Cotiza con ficha técnica."},
  "/equipo-de-respiracion-autonoma/mascaras-y-reguladores-era/": {"title": "Máscara y regulador para equipo de respiración autónoma", "description": "Máscaras y reguladores para ERA: sello facial, copa nasal, tallas, prueba de ajuste, regulador de demanda e interfaz con casco y capucha. Cotiza con ficha."},
  "/equipo-de-respiracion-autonoma/era-de-escape/": {"title": "ERA de escape EEBD para evacuación de corta duración", "description": "ERA de escape para evacuación: equipos EEBD de corta duración, ruta de salida, entrenamiento y límites frente a un ERA de combate. Cotiza con ficha técnica."},
  "/equipo-de-respiracion-autonoma/era-industrial/": {"title": "ERA industrial NIOSH para brigadas y espacios confinados", "description": "ERA industrial para brigadas y espacios confinados: certificación NIOSH, cilindro, máscara, arnés y límites frente al combate estructural. Cotiza con ficha."},
  "/equipo-de-respiracion-autonoma/msa-g1-industrial/": {"title": "ERA MSA G1 Industrial NIOSH de 60 minutos", "description": "Equipo de respiración autónoma MSA G1 Industrial: NIOSH 42 CFR Parte 84, cilindro DOT de 4,500 psi y 60 min nominales para brigadas. Cotiza con ficha.", "h1": "ERA MSA G1 Industrial con certificación NIOSH"},
  "/equipo-de-respiracion-autonoma/skold-phantom/": {"title": "ERA Sköld Phantöm de 60 minutos y 4,500 psi", "description": "Equipo de respiración autónoma Sköld Phantöm: 60 min nominales, 4,500 psi, máscara panorámica y reguladores, con la norma que declara el fabricante.", "h1": "ERA Sköld Phantöm de 60 minutos"},
  "/botas/bota-de-hule-estructural/": {"title": "Bota de hule estructural para bombero con puntera", "description": "Bota de hule estructural para bombero: caucho vulcanizado, puntera, entresuela antiperforación, forro aislante y revisión de talla. Cotiza con ficha técnica."},
  "/botas/bota-de-piel-estructural/": {"title": "Bota de piel estructural para bombero con membrana", "description": "Bota de piel estructural para bombero: ajuste, membrana, protección térmica, suela y criterios para comparar una configuración de ataque interior. Cotiza."},
  "/botas/bota-forestal/": {"title": "Bota forestal para bombero y brigadista de línea de fuego", "description": "Bota forestal para bombero y brigadista: piel, agujetas, caña, suela de alta temperatura y selección segura para caminar en línea de fuego. Cotiza."},
  "/botas/bota-de-brigada-industrial/": {"title": "Bota para brigada industrial contra incendio", "description": "Bota para brigada industrial contra incendio: calzado de seguridad, riesgo de conato, NOM-113-STPS-2009 y cuándo se requiere bota de bombero. Cotiza."},
  "/botas/croydon-filtrex/": {"title": "Bota de bombero Croydon Filtrex BOT1002 de hule", "description": "Bota de bombero Croydon Filtrex BOT1002 de hule estructural, 13 pulgadas, tallas 25 a 31 cm, con puntera y entresuela de acero declaradas. Cotiza.", "h1": "Bota de bombero Croydon Filtrex BOT1002"},
  "/botas/romak-workman-fire/": {"title": "Bota de bombero Romak Fire Workman Fire BOT1004", "description": "Bota de bombero Romak Fire Workman Fire BOT1004 de caucho vulcanizado, 33 cm, tallas 26 a 31 cm, con puntera y entresuela de acero declaradas. Cotiza.", "h1": "Bota de bombero Romak Fire Workman Fire BOT1004"},
  "/botas/skold-workman/": {"title": "Botas de bombero Sköld Workman FPBSK de caucho", "description": "Botas de bombero Sköld Workman FPBSK: caucho natural, 3,150 g, caña de 13 pulgadas, puntera y entresuela de acero. Cotiza por talla con ficha técnica."},
  "/botas/romak-fire-ranger-bota/": {"title": "Bota forestal Romak Fire Ranger de piel y caña alta", "description": "Bota forestal Romak Fire Ranger de piel negra, agujetas y caña alta para brigadista. Solicita ficha técnica, código y alcance antes de definir su uso.", "h1": "Bota forestal Romak Fire Ranger para brigadista"},
  "/botas/strongfire-bota-forestal/": {"title": "Bota forestal Strong Fire de piel con planta de Kevlar", "description": "Bota forestal Strong Fire de piel hidrofugada, tubo de 24 cm según talla, planta de Kevlar y suela de hule acrilonitrilo declaradas. Cotiza con ficha.", "h1": "Bota forestal Strong Fire de caña corta"},
  "/guantes/guante-estructural/": {"title": "Guantes de bombero estructural con barrera de humedad", "description": "Guantes de bombero estructural: capas, barreras, puño, ajuste y referencia NFPA 1970 para comparar una cotización institucional por operación."},
  "/guantes/guante-brigadista/": {"title": "Guante para brigadista contra incendio y conato", "description": "Guante para brigadista contra incendio: materiales, ajuste y límites de uso para definir el equipo de respuesta inicial y pedir una cotización clara."},
  "/guantes/guante-forestal/": {"title": "Guante forestal para bombero de línea de fuego", "description": "Guante forestal para bombero: movilidad, puño, calor exterior y referencia NFPA 1950 antes de integrar el equipo de línea de fuego. Cotiza con ficha."},
  "/guantes/guante-rescate-extricacion/": {"title": "Guante de rescate y extricación para bombero", "description": "Guante de rescate y extricación para bombero: agarre, destreza, riesgo mecánico y referencia NFPA 1950 antes de solicitar una cotización por operación."},
  "/guantes/romak-firemax-vi/": {"title": "Guante de bombero Romak Fire Firemax VI para brigadista", "description": "Guante Romak Fire Firemax VI para brigadista: material, construcción, talla y estatus normativo para revisar ajuste e interfaz con el traje. Cotiza.", "h1": "Guante Romak Fire Firemax VI para brigadista"},
  "/guantes/skold-fpgs/": {"title": "Guante de bombero Sköld FPGS estructural", "description": "Guante de bombero Sköld FPGS: material, construcción, talla y estatus normativo para revisar ajuste e interfaz con el chaquetón. Cotiza con ficha técnica.", "h1": "Guante de bombero Sköld FPGS"},
  "/guantes/veridian-fire-pro-ii/": {"title": "Guante estructural Veridian Fire Pro II para bombero", "description": "Guante estructural Veridian Fire Pro II: material, construcción, talla y estatus normativo para revisar ajuste e interfaz con el traje. Cotiza con ficha.", "h1": "Guante estructural Veridian Fire Pro II para bombero"},
  "/capuchas/majestic-pac-ii/": {"title": "Monja para bombero Majestic PAC II de Nomex", "description": "Monja para bombero Majestic PAC II: material, capas, apertura facial y cuidado para validar la interfaz con ERA, casco y chaquetón antes de cotizar.", "h1": "Monja para bombero Majestic PAC II"},
  "/capuchas/romak-cap1005/": {"title": "Monja para bombero Romak Fire CAP1005 over-face", "description": "Monja para bombero Romak Fire CAP1005 over-face: material, capas, apertura facial y cuidado para validar la interfaz con ERA, casco y chaquetón.", "h1": "Monja para bombero Romak Fire CAP1005 over-face"},
  "/capuchas/skold-fpen/": {"title": "Escafandra Nomex Sköld FPEN: monja para bombero", "description": "Escafandra Nomex Sköld FPEN para bombero: material, capas, apertura facial y cuidado para validar la interfaz con ERA, casco y chaquetón. Cotiza.", "h1": "Escafandra Nomex Sköld FPEN para bombero"},
  "/accesorios/lampara-de-casco/": {"title": "Lámpara de casco para bombero con manos libres", "description": "Lámpara de casco para bombero: deja las manos libres y debe apuntar sin estorbar visor, máscara ni retención. Compatibilidad con tu casco al cotizar."},
  "/accesorios/linterna-de-bombero/": {"title": "Linterna de bombero para uso con guante estructural", "description": "Linterna de bombero: se elige por agarre, interruptor, energía y forma de llevarla con guante en la escena. Revisa la ficha técnica y cotiza la partida."},
  "/accesorios/goggles/": {"title": "Goggles para bombero forestal y de rescate", "description": "Goggles para bombero: lente, marco y correa que conservan la visión en una exposición definida, forestal o de rescate. Compatibilidad con el casco al cotizar."},
  "/accesorios/camara-termica/": {"title": "Cámara térmica para bomberos: búsqueda y ataque", "description": "Cámara térmica para bomberos: muestra contrastes de radiación infrarroja y exige entrenamiento para leerlos en la escena. Cotiza con ficha técnica."},
  "/accesorios/dispositivo-pass/": {"title": "Dispositivo PASS para bombero: alarma personal", "description": "Dispositivo PASS para bombero: alerta personal de inmovilidad dentro de una respuesta institucional que debe estar ensayada. Cotiza con ficha técnica."},
  "/accesorios/maleta-porta-equipo/": {"title": "Maleta porta-equipo para bombero y traje completo", "description": "Maleta porta-equipo para bombero: organiza el traslado del conjunto y se valida cargando casco, botas, prendas y accesorios reales. Cotiza con ficha técnica."},
  "/accesorios/streamlight-vantage/": {"title": "Lámpara de casco Streamlight Vantage para bombero", "description": "Lámpara de casco Streamlight Vantage para bombero: LED C4, giro de 360°, clip para el ala del casco y dos CR123A incluidas. Compatibilidad al cotizar.", "h1": "Lámpara de casco Streamlight Vantage para bombero"},
  "/accesorios/ess-striketeam-xto/": {"title": "Goggles ESS Striketeam XTO para bombero forestal", "description": "Goggles ESS Striketeam XTO para bombero forestal: Speed-Clip, ventilación perimetral, lente intercambiable y normas declaradas por el fabricante. Cotízalos.", "h1": "Goggles ESS Striketeam XTO para bombero forestal"},
  "/accesorios/romak-bps1005/": {"title": "Maleta porta-equipo Romak Fire BPS1005 para bombero", "description": "Maleta porta-equipo Romak Fire BPS1005 en poliéster repelente al agua para trasladar el conjunto del bombero: casco, botas, prendas y accesorios.", "h1": "Maleta porta-equipo Romak Fire BPS1005 para bombero"},
  "/herramientas/hacha-de-bombero/": {"title": "Hacha de bombero para acceso y entrada forzada", "description": "Hacha de bombero para acceso y entrada forzada: corte y golpe en una pieza. Define cabeza, mango, peso declarado y resguardo antes de cotizar la partida.", "h1": "Hacha de bombero para acceso y entrada forzada", "lead": "El hacha para bombero combina corte y golpe en maniobras autorizadas de acceso y entrada forzada. Define cabeza, mango, peso y resguardo según la operación.", "faqsExtra": [{"q": "¿Para qué sirve el hacha de bombero?", "a": "Combina corte y golpe para maniobras autorizadas de acceso, entrada forzada y retiro de material. Se elige por el tipo de cabeza, el material y largo del mango y el peso, y se resguarda en la unidad dentro de un programa de mantenimiento."}, {"q": "¿Cuánto pesa un hacha de bombero?", "a": "El peso depende del modelo, de la cabeza y del mango. Esta ficha no publica un modelo ni un peso único, por lo que no sería correcto dar una cifra general. Al cotizar, pide el peso declarado, largo, tipo de cabeza y método de resguardo para compararlos con tu maniobra."}]},
  "/herramientas/barra-halligan/": {"title": "Herramienta Halligan para bombero y entrada forzada", "description": "Herramienta Halligan para bombero: entrada forzada, largo, material, mantenimiento y resguardo. Solicita la ficha técnica para cotizar.", "h1": "Herramienta Halligan para bombero y entrada forzada", "lead": "La herramienta Halligan para bombero sirve en entrada forzada y rescate. Define largo, material, garra y resguardo con base en las maniobras autorizadas de tu corporación.", "faqsExtra": [{"q": "¿Qué significa Halligan?", "a": "Halligan es el nombre de una barra de entrada forzada usada por bomberos. Combina una garra, una cuña y una punta para aplicar palanca, separar elementos o crear acceso. No sustituye la capacitación: su uso se define por la maniobra, la escena y el procedimiento de la corporación."}, {"q": "¿Para qué se utiliza un Halligan?", "a": "Se utiliza en entrada forzada para aplicar palanca y crear acceso cuando la maniobra está autorizada. También puede apoyar trabajos de rescate según la técnica entrenada. La compra debe definir largo, material y configuración, además del método de resguardo seguro en la unidad."}]},
  "/herramientas/gancho-bichero/": {"title": "Gancho bichero para bombero: alcance y remoción", "description": "Gancho bichero para bombero: alcanzar, jalar o revisar desde una posición segura; largo, cabezal, control, mantenimiento y datos para cotizar la partida."},
  "/herramientas/pulaski/": {"title": "Pulaski: herramienta forestal de hacha y azadón", "description": "Pulaski para bombero forestal: hacha y azadón en una sola cabeza para brecha y línea de control. Selección, mango, afilado, resguardo y datos para cotizar.", "h1": "Pulaski: herramienta forestal para bombero"},
  "/herramientas/mcleod/": {"title": "McLeod: herramienta forestal de rastrillo y azadón", "description": "McLeod para bombero forestal: rastrillo y azadón para raspar la línea de control hasta suelo mineral. Define pala, mango y mantenimiento y cotiza.", "h1": "McLeod: herramienta forestal para bombero", "faqsExtra": [{"q": "¿Qué es un McLeod?", "a": "El McLeod es una herramienta forestal que combina rastrillo y azadón en una misma cabeza. Sirve para raspar combustible y trabajar la línea de control hasta suelo mineral. Se selecciona por la forma de la pala, el mango y el uso que realizará la brigada en campo."}, {"q": "¿Qué significa McLeod en herramientas forestales?", "a": "En el contexto forestal, McLeod nombra una herramienta de doble función, con dientes de rastrillo por un lado y filo de azadón por el otro. No describe un tipo de rastrillo de jardín. Su mantenimiento incluye limpiar la cabeza, revisar el mango y resguardarla correctamente."}]},
  "/herramientas/batefuego/": {"title": "Batefuego para combate de incendio forestal", "description": "Batefuego para bombero forestal: sofocar fuego de pasto y material ligero; paleta, mango, peso, mantenimiento y resguardo. Datos para cotizar la partida.", "h1": "Batefuego: herramienta forestal para bombero"},
  "/herramientas/rastrillo-forestal/": {"title": "Rastrillo forestal con mango para bombero y brigada", "description": "Rastrillo forestal con mango para limpiar combustible ligero en la línea de control. Define dientes, mango y mantenimiento antes de cotizar.", "h1": "Rastrillo forestal con mango para bombero", "lead": "El rastrillo forestal con mango retira combustible ligero en la línea de control. Revisa dientes, pala, mango y resguardo según el terreno y la tarea de la brigada.", "faqsExtra": [{"q": "¿Qué es un rastrillo forestal y para qué se utiliza?", "a": "Es una herramienta de brigada para retirar combustible ligero y apoyar la construcción de una línea de control en incendio forestal. No se selecciona como un rastrillo de jardinería. La pala, los dientes y el mango deben corresponder al terreno y a la técnica que practica tu equipo."}, {"q": "¿Qué características tiene un rastrillo forestal?", "a": "La ficha debe describir forma y material de la pala, cantidad y disposición de dientes, tipo y longitud de mango y método de resguardo. Estos datos determinan cómo mueve combustible ligero y cómo se transporta. Te confirmamos cada dato con la ficha del fabricante antes de cotizar."}]},
  "/herramientas/bomba-de-mochila-forestal/": {"title": "Bomba de mochila forestal para incendio de vegetación", "description": "Bomba de mochila forestal para bombero: agua para apoyo puntual en vegetación; capacidad, arnés y mantenimiento que la hacen confiable. Datos para cotizar."},
  "/herramientas/romak-hac1007/": {"title": "Barra Halligan Romak Fire HAC1007 de acero inoxidable", "description": "Barra Halligan Romak Fire HAC1007 de acero inoxidable, 91 cm y 6 lb, para rescate y entrada forzada. Consulta configuración y cotiza con ficha técnica.", "h1": "Barra Halligan Romak Fire HAC1007 para bombero"},
  "/rescate/herramienta-hidraulica-de-rescate/": {"title": "Quijadas de la vida: equipo hidráulico de rescate", "description": "Quijadas de la vida y equipo hidráulico para extricación: separador, cortador y cilindro. Define el sistema y cotiza con ficha técnica.", "h1": "Equipo hidráulico de rescate y quijadas de la vida", "lead": "Las quijadas de la vida son equipo hidráulico de rescate para extricación de personas atrapadas. Separador, cortador, combinada y cilindro cumplen maniobras distintas dentro del sistema.", "faqsExtra": [{"q": "¿Qué son las quijadas de la vida?", "a": "Es el nombre con el que se conoce a la herramienta hidráulica de rescate. Incluye separadores, cortadores, herramientas combinadas y cilindros que abren, cortan o empujan la estructura de un vehículo para liberar a una persona atrapada. Cada pieza trabaja con el sistema de potencia que declara su fabricante."}, {"q": "¿Cómo funcionan las quijadas de la vida?", "a": "Funcionan mediante un sistema hidráulico o de batería, según el equipo seleccionado. El separador abre y crea espacio, el cortador trabaja postes y perfiles, y el cilindro empuja. La maniobra inicia tras estabilizar el vehículo y controlar la escena, siempre con personal entrenado."}]},
  "/rescate/arnes-de-rescate/": {"title": "Arnés de rescate para bomberos y trabajo en altura", "description": "Arnés de rescate y seguridad para trabajo en altura: clases, anclajes, talla e inspección. Revisa la maniobra y cotiza con ficha técnica.", "h1": "Arnés de rescate para trabajo en altura", "lead": "El arnés de rescate es un arnés de cuerpo completo para maniobras con cuerda y trabajo en altura. Se elige por clase, talla, anclajes y compatibilidad con el sistema.", "faqsExtra": [{"q": "¿Qué es un arnés de rescate?", "a": "Es un arnés de cuerpo completo que une al rescatista con un sistema de cuerda durante acceso, descenso, ascenso o posicionamiento. Se diferencia de un arnés industrial de protección contra caídas porque la clase y los puntos de conexión deben corresponder a la maniobra de rescate."}, {"q": "¿Qué dice la norma ANSI Z359?", "a": "ANSI Z359 es una referencia industrial para sistemas de protección contra caídas. En bomberos, la ficha usa NFPA 2500 como referencia para equipo de rescate con cuerda. Ninguna norma sustituye revisar lo que declara el modelo, su clase, sus anclajes y la compatibilidad con la línea de vida."}]},
  "/rescate/cuerda-de-rescate/": {"title": "Cuerda de rescate estática para trabajo en altura", "description": "Cuerda de rescate estática kernmantle para trabajo en altura: diámetro, longitud e inspección. Define la función y cotiza con ficha técnica.", "h1": "Cuerda de rescate estática para trabajo en altura", "lead": "La cuerda de rescate estática kernmantle se usa en trabajo en altura y rescate vertical. Se define por diámetro, longitud, terminaciones y compatibilidad con el sistema.", "faqsExtra": [{"q": "¿Qué es una cuerda de rescate?", "a": "Es una cuerda usada dentro de un sistema de rescate para descenso, ascenso, izado o aseguramiento. Esta ficha aborda cuerda estática tipo kernmantle, cuya construcción combina núcleo portante y funda protectora. Se selecciona por diámetro, longitud y compatibilidad con descensores, conectores y anclajes."}, {"q": "¿Qué tipos de cuerdas de rescate existen?", "a": "Para rescate con cuerda se distinguen por su función dentro del sistema, como línea principal, respaldo o acceso. Esta página se refiere a cuerda estática kernmantle. La cuerda dinámica de escalada se estira para absorber caídas y no se debe intercambiar sin revisar el procedimiento y el equipo."}]},
  "/rescate/mosquetones-de-rescate/": {"title": "Mosquetones de seguridad para rescate de bomberos", "description": "Mosquetones de seguridad para rescate: acero o aluminio, seguro automático o de rosca, resistencia marcada y compatibilidad del sistema. Cotiza con ficha.", "lead": "Los mosquetones de seguridad para rescate se comparan por material, tipo de seguro, forma y resistencia marcada por el fabricante para el sistema donde se emplearán.", "faqsExtra": [{"q": "¿Qué tipos de mosquetones de seguridad hay para rescate?", "a": "Se distinguen por material (acero o aluminio), por seguro (de rosca o automático) y por forma (en D, D asimétrico u oval). En rescate se eligen por la resistencia marcada en el cuerpo del mosquetón y por su compatibilidad con cuerda, placa y polea; un mosquetón de llavero o decorativo no sirve para cargar personas."}]},
  "/rescate/kit-de-rescate-vertical/": {"title": "Kit de rescate vertical para bomberos con cuerda y arnés", "description": "Kit de rescate vertical para bomberos con cuerda, arnés, descensor, poleas y anclajes compatibles. Define la técnica de rescate y cotiza con ficha técnica.", "h1": "Kit de rescate vertical y técnicas de rescate", "lead": "El kit de rescate vertical reúne cuerda, arnés, descensor, poleas y anclajes para una técnica de rescate definida. La seguridad depende de que todos los componentes sean compatibles.", "faqsExtra": [{"q": "¿Qué significa rescate vertical?", "a": "Rescate vertical es el conjunto de técnicas para acceder, descender, ascender, asegurar o recuperar personas mediante sistemas de cuerda. Puede realizarse en altura, desniveles o espacios donde no hay acceso directo. El kit se configura por escenario, maniobra, número de usuarios y compatibilidad entre sus componentes."}, {"q": "¿Qué tipos de rescate en altura existen?", "a": "Las maniobras pueden incluir acceso por cuerda, descenso, ascenso, izado y evacuación horizontal asistida. La técnica correcta depende del escenario y del entrenamiento del equipo. No conviene comprar un kit genérico: define primero las técnicas que practica tu corporación y pide la ficha de cada componente."}]},
  "/mangueras-y-accesorios/manguera-de-ataque/": {"title": "Manguera de bombero de ataque contra incendio", "description": "Manguera de bombero de ataque contra incendio de 1 ½ o 2 ½ pulgadas, con acoples y doble chaqueta según configuración. Cotiza con ficha técnica.", "h1": "Manguera de bombero de ataque contra incendio", "lead": "La manguera de bombero de ataque conduce agua de la bomba al pitón. Se selecciona por diámetro, longitud, doble chaqueta, acoples y rosca compatibles con la línea.", "faqsExtra": [{"q": "¿Cómo se llama la manguera que utilizan los bomberos?", "a": "La línea que lleva agua al pitón se conoce como manguera de ataque. Se pide por diámetro, longitud, construcción, acoples y rosca. Esta ficha contempla 1 ½ y 2 ½ pulgadas, con doble chaqueta según la configuración; el modelo final debe confirmar los datos técnicos."}, {"q": "¿Qué características hay que considerar al elegir una manguera de bombero?", "a": "Revisa el diámetro, la longitud de cada tramo, la construcción, los acoples y la rosca que ya usa tu bomba y tu pitón. También confirma el uso de la línea y la norma que declare el fabricante. No mezcles medidas o roscas sin adaptadores previstos."}]},
  "/mangueras-y-accesorios/piton-boquilla/": {"title": "Chiflón para manguera contra incendio: pitón o boquilla", "description": "Chiflón para manguera contra incendio: pitón o boquilla de chorro y niebla, caudal, conexión y mantenimiento. Datos para cotizar la partida con ficha.", "h1": "Chiflón, pitón o boquilla para manguera contra incendio", "lead": "El chiflón para manguera contra incendio, también llamado pitón o boquilla, se selecciona por patrón de chorro o niebla, caudal declarado y acople compatible con la manguera y la maniobra.", "faqsExtra": [{"q": "¿Qué es un chiflón para manguera contra incendio?", "a": "Es la boquilla que va al final de la manguera y controla la descarga: abre, cierra y define el patrón de chorro directo, niebla o combinado. En México se le llama chiflón, pitón o boquilla; se elige por caudal declarado, presión de trabajo y el acople de la manguera."}, {"q": "¿Sirve un chiflón de jardín para una manguera contra incendio?", "a": "No. Un chiflón de jardín no está construido para la presión, el caudal ni los acoples de una línea contra incendio. Para gabinete, hidrante o autobomba se especifica un pitón contra incendio con su ficha técnica y el diámetro de la manguera."}]},
  "/mangueras-y-accesorios/llave-para-hidrante/": {"title": "Llave para hidrante contra incendio y llaves spanner", "description": "Llave para hidrante contra incendio y llaves spanner: tipo de operación, tamaño de conexiones y compatibilidad con los elementos instalados. Cotiza con ficha."},
  "/mangueras-y-accesorios/conexiones-y-adaptadores/": {"title": "Conexiones y adaptadores para manguera contra incendio", "description": "Conexiones y adaptadores contra incendio: reducciones, siamesas y adaptadores por rosca, diámetro y flujo requerido, sin asumir equivalencias. Cotiza."},
  "/kits/kit-estructural/": {"title": "Kit de bombero estructural: traje, casco, botas y guantes", "description": "Kit de bombero estructural con traje, casco, monja, guantes y botas para revisar cobertura, tallas e interfaz en una sola partida. Cotiza con ficha técnica."},
  "/kits/kit-brigadista/": {"title": "Kit de brigadista contra incendio NOM-002-STPS", "description": "Kit brigadista contra incendio con traje, casco, capucha, guantes y botas para definir una partida conforme al riesgo y procedimiento del centro de trabajo."},
  "/kits/kit-forestal/": {"title": "Kit forestal para brigada y bombero de línea de fuego", "description": "Kit forestal con ropa, casco, goggles, guantes, bota y nuquera para armar la protección de línea de fuego según la tarea de la cuadrilla. Cotiza con ficha."},
  "/marcas/": {"title": "Marcas de equipo para bombero: Romak Fire y Sköld", "description": "Marcas de equipo para bombero que cotizamos: Romak Fire y Sköld, con trajes, cascos, botas, guantes y ERA configurados según cada operación."},
  "/marcas/romak-fire/": {"title": "Romak Fire: trajes para bombero y equipo contra incendio", "description": "Romak Fire: trajes para bombero estructurales, de brigadista, forestales y de aproximación, más botas, guantes y herramientas. Consulta modelos y cotiza.", "h1": "Romak Fire: trajes y equipo para bombero"},
  "/marcas/skold/": {"title": "Sköld: trajes, cascos, botas y ERA para bombero", "description": "Sköld: trajes, casco, bota, guantes, escafandra y ERA para bombero. Revisa los modelos publicados, su estatus normativo y su documentación al cotizar.", "h1": "Sköld: trajes y equipo para bombero"},
};

export const metaSeo = (path: string): MetaSeo | undefined => METAS_SEO[path];
