// ============================================================
// METAS SEO por ruta — tanda de metas página por página (2026-09-29).
// Title sin marca, sin «México» y sin «|»; description 135–158 con CTA;
// keywords de Ahrefs MX (web). Tiene prioridad sobre title/description
// de los datos del catálogo (secciones, tipos y modelos de complementos).
// Bitácora: OBSIDIAN/TRAJESBOMBERO/15-Metas-y-SEO-pagina-por-pagina.
// ============================================================
export interface MetaSeo {
  title: string;
  description: string;
  h1?: string;
  lead?: string;                         // lead del hero con la keyword principal
  faqsExtra?: { q: string; a: string }[]; // preguntas de la SERP (Ahrefs) que se anteponen a las FAQ
}

export const METAS_SEO: Record<string, MetaSeo> = {
  "/cascos/casco-estructural-tradicional/": {"title": "Casco estructural tradicional para bombero estilo americano", "description": "Casco estructural tradicional para bombero: componentes, norma de referencia, compatibilidad con ERA y qué pedir al cotizar un casco de ataque interior."},
  "/cascos/casco-estructural-europeo/": {"title": "Casco estructural europeo tipo jet para bombero EN 443", "description": "Casco estructural europeo tipo jet: cobertura, visor integrado, compatibilidad con ERA y referencia EN 443:2008 para evaluar una cotización de bomberos."},
  "/cascos/casco-forestal/": {"title": "Casco forestal para bombero ligero y de ala completa", "description": "Casco forestal para bombero: peso, ala completa, ventilación, clips para goggles y norma de referencia para trabajo prolongado en línea de fuego. Cotiza."},
  "/cascos/casco-rescate-tecnico/": {"title": "Casco de rescate técnico para bombero y rescate vertical", "description": "Casco de rescate técnico: perfil compacto, retención de cuatro puntos y lámpara para rescate vehicular, vertical y espacios confinados. Cotiza con ficha."},
  "/cascos/casco-brigada-industrial/": {"title": "Casco para brigada industrial contra incendio", "description": "Casco para brigada industrial contra incendio: cuándo basta un casco industrial y cuándo el riesgo exige casco estructural para combate interior. Cotiza."},
  "/cascos/bullard-ltx/": {"title": "Casco Bullard LTX estructural con visor y ratchet", "description": "Casco Bullard LTX estructural con visor, ajuste ratchet y suspensión de seis puntos. Revisa la configuración y cotiza con ficha técnica.", "h1": "Casco Bullard LTX estructural con visor", "lead": "El casco Bullard LTX usa carcasa de termoplástico de alto impacto, ajuste ratchet y suspensión de seis puntos. Confirma color, visor y compatibilidad con tu ERA antes de cotizar.", "faqsExtra": [{"q": "¿Qué protege un casco Bullard LTX?", "a": "El LTX está publicado como casco estructural para combate de incendios. Su ficha declara carcasa de termoplástico de alto impacto, cubrenuca de Nomex y visor de policarbonato. La protección efectiva depende de que se use con el conjunto compatible, incluyendo máscara de ERA, capucha y barbiquejo ajustado."}, {"q": "¿Cómo se ajusta el casco Bullard LTX?", "a": "El modelo declara ajuste ratchet y suspensión de seis puntos. La prueba se hace con máscara, capucha y chaquetón puestos. Ajusta la perilla y revisa que el casco no gire al mirar hacia arriba. Si el visor desplaza la máscara, corrige la configuración antes de asignarlo."}]},
  "/cascos/bullard-ust-lw/": {"title": "Casco Bullard UST LW ultraligero con visor ReTrack", "description": "Casco Bullard UST LW ultraligero de fibra de vidrio, con ajuste Sure-Lock y visor ReTrack. Define la protección ocular y cotiza con ficha técnica.", "h1": "Casco Bullard UST LW ultraligero con ReTrack", "lead": "El casco Bullard UST LW es un modelo estructural de estilo Nueva York con fibra de vidrio, ajuste Sure-Lock y visor ReTrack. Define la protección ocular antes de cotizar.", "faqsExtra": [{"q": "¿Qué distingue al casco Bullard UST LW?", "a": "El UST LW se diferencia por su estilo Nueva York ultraligero, carcasa de fibra de vidrio y ajuste Sure-Lock. Su ficha declara menos de 1.54 kg con visor ReTrack. No comparte la carcasa termoplástica ni el visor de cuatro pulgadas del LTX, por lo que conviene probar ambos con el ERA."}, {"q": "¿Qué protección ocular puede llevar el Bullard UST LW?", "a": "La ficha del UST LW declara visor integrado ReTrack y opción de careta o goggles. Cada alternativa cambia la configuración y el peso publicado. Define la opción antes de pedir cotización y pruébala con la máscara de ERA para comprobar que no interfiera con el campo de visión."}]},
  "/cascos/bullard-fh911h/": {"title": "Casco forestal Bullard Wildland FH911H para bombero", "description": "Casco forestal Bullard Wildland FH911H: suspensión de seis puntos y clips para goggles, ligero para línea de fuego. Cotiza con ficha técnica y configuración.", "h1": "Casco forestal Bullard Wildland FH911H"},
  "/cascos/skold-viking/": {"title": "Casco de bombero Sköld Viking FPCM con protector facial", "description": "Casco de bombero Sköld Viking FPCM estructural: ajuste de matraca, barbiquejo de cuatro puntos y protector facial. Cotiza con ficha técnica y configuración."},
  "/equipo-de-respiracion-autonoma/era-de-combate/": {"title": "ERA para combate de incendios con PASS y alarmas", "description": "ERA para combate de incendios: autonomía nominal, PASS, alarmas, máscara y referencia NFPA 1970 para revisar una cotización institucional de bomberos."},
  "/equipo-de-respiracion-autonoma/cilindros-de-fibra-de-carbono/": {"title": "Cilindros de fibra de carbono para ERA de 4,500 psi", "description": "Cilindros de fibra de carbono para ERA: 4,500 psi, duración nominal, etiqueta DOT, válvula, conexión y prueba hidrostática. Cotiza con ficha técnica."},
  "/equipo-de-respiracion-autonoma/mascaras-y-reguladores-era/": {"title": "Máscara y regulador para equipo de respiración autónoma", "description": "Máscaras y reguladores para ERA: sello facial, copa nasal, tallas, prueba de ajuste, regulador de demanda e interfaz con casco y capucha. Cotiza con ficha."},
  "/equipo-de-respiracion-autonoma/era-de-escape/": {"title": "ERA de escape EEBD para evacuación de corta duración", "description": "ERA de escape para evacuación: equipos EEBD de corta duración, ruta de salida, entrenamiento y límites frente a un ERA de combate. Cotiza con ficha técnica."},
  "/equipo-de-respiracion-autonoma/era-industrial/": {"title": "ERA industrial NIOSH para brigadas y espacios confinados", "description": "ERA industrial para brigadas y espacios confinados: certificación NIOSH, cilindro, máscara, arnés y límites frente al combate estructural. Cotiza con ficha."},
  "/equipo-de-respiracion-autonoma/msa-g1-industrial/": {"title": "ERA MSA G1 Industrial NIOSH de 60 minutos", "description": "Equipo de respiración autónoma MSA G1 Industrial: NIOSH 42 CFR Parte 84, cilindro DOT de 4,500 psi y 60 min nominales para brigadas. Cotiza con ficha.", "h1": "ERA MSA G1 Industrial con certificación NIOSH"},
  "/equipo-de-respiracion-autonoma/skold-phantom/": {"title": "ERA Sköld Phantöm de 60 minutos y 4,500 psi", "description": "Equipo de respiración autónoma Sköld Phantöm: 60 min nominales, 4,500 psi, máscara panorámica y reguladores, con la norma que declara el fabricante.", "h1": "ERA Sköld Phantöm de 60 minutos"},
  "/botas/bota-de-hule-estructural/": {"title": "Bota de hule estructural para bombero con puntera", "description": "Bota de hule estructural para bombero: caucho vulcanizado, puntera, entresuela antiperforación, forro aislante y revisión de talla. Cotiza con ficha técnica."},
  "/botas/bota-de-piel-estructural/": {"title": "Bota de piel estructural para bombero con membrana", "description": "Bota de piel estructural para bombero: ajuste, membrana, protección térmica, suela y criterios para comparar una configuración de ataque interior. Cotiza."},
  "/botas/bota-forestal/": {"title": "Bota forestal para bombero y brigadista de línea de fuego", "description": "Bota forestal para bombero y brigadista: piel, agujetas, caña, suela de alta temperatura y selección segura para caminar en línea de fuego. Cotiza."},
  "/botas/bota-de-brigada-industrial/": {"title": "Bota para brigada industrial contra incendio", "description": "Bota para brigada industrial contra incendio: calzado de seguridad, riesgo de conato, NOM-113-STPS-2009 y cuándo se requiere bota de bombero. Cotiza."},
  "/botas/croydon-filtrex/": {"title": "Bota de bombero Croydon Filtrex BOT1002 de hule", "description": "Bota de bombero Croydon Filtrex BOT1002 de hule estructural, 13 pulgadas, tallas 25 a 31 cm, con puntera y entresuela de acero declaradas. Cotiza.", "h1": "Bota de bombero Croydon Filtrex BOT1002"},
  "/botas/romak-workman-fire/": {"title": "Bota de bombero Romak Fire Workman Fire BOT1004", "description": "Bota de bombero Romak Fire Workman Fire BOT1004 de caucho vulcanizado, 33 cm, tallas 26 a 31 cm, con puntera y entresuela de acero declaradas. Cotiza.", "h1": "Bota de bombero Romak Fire Workman Fire BOT1004"},
  "/botas/skold-workman/": {"title": "Botas de bombero Sköld Workman FPBSK de caucho", "description": "Botas de bombero Sköld Workman FPBSK: caucho natural, 3,150 g, caña de 13 pulgadas, puntera y entresuela de acero. Cotiza por talla con ficha técnica."},
  "/botas/romak-fire-ranger-bota/": {"title": "Bota forestal Romak Fire Ranger de piel y caña alta", "description": "Bota forestal Romak Fire Ranger de piel negra, agujetas y caña alta para brigadista. Solicita ficha técnica, código y alcance antes de definir su uso.", "h1": "Bota forestal Romak Fire Ranger para brigadista"},
  "/botas/strongfire-bota-forestal/": {"title": "Bota forestal Strong Fire de piel con planta de Kevlar", "description": "Bota forestal Strong Fire de piel hidrofugada, tubo de 24 cm según talla, planta de Kevlar y suela de hule acrilonitrilo declaradas. Cotiza con ficha.", "h1": "Bota forestal Strong Fire de caña corta"},
  "/guantes/guante-estructural/": {"title": "Guantes de bombero estructural con barrera de humedad", "description": "Guantes de bombero estructural: capas, barreras, puño, ajuste y referencia NFPA 1970 para comparar una cotización institucional por operación."},
  "/guantes/guante-brigadista/": {"title": "Guante para brigadista contra incendio y conato", "description": "Guante para brigadista contra incendio: materiales, ajuste y límites de uso para definir el equipo de respuesta inicial y pedir una cotización clara."},
  "/guantes/guante-forestal/": {"title": "Guante forestal para bombero de línea de fuego", "description": "Guante forestal para bombero: movilidad, puño, calor exterior y referencia NFPA 1950 antes de integrar el equipo de línea de fuego. Cotiza con ficha."},
  "/guantes/guante-rescate-extricacion/": {"title": "Guante de rescate y extricación para bombero", "description": "Guante de rescate y extricación para bombero: agarre, destreza, riesgo mecánico y referencia NFPA 1950 antes de solicitar una cotización por operación."},
  "/guantes/romak-firemax-vi/": {"title": "Guante de bombero Romak Fire Firemax VI para brigadista", "description": "Guante Romak Fire Firemax VI para brigadista: material, construcción, talla y estatus normativo para revisar ajuste e interfaz con el traje. Cotiza.", "h1": "Guante Romak Fire Firemax VI para brigadista"},
  "/guantes/skold-fpgs/": {"title": "Guante de bombero Sköld FPGS estructural", "description": "Guante de bombero Sköld FPGS: material, construcción, talla y estatus normativo para revisar ajuste e interfaz con el chaquetón. Cotiza con ficha técnica.", "h1": "Guante de bombero Sköld FPGS"},
  "/guantes/veridian-fire-pro-ii/": {"title": "Guante estructural Veridian Fire Pro II para bombero", "description": "Guante estructural Veridian Fire Pro II: material, construcción, talla y estatus normativo para revisar ajuste e interfaz con el traje. Cotiza con ficha.", "h1": "Guante estructural Veridian Fire Pro II para bombero"},
  "/capuchas/majestic-pac-ii/": {"title": "Monja para bombero Majestic PAC II de Nomex", "description": "Monja para bombero Majestic PAC II: material, capas, apertura facial y cuidado para validar la interfaz con ERA, casco y chaquetón antes de cotizar.", "h1": "Monja para bombero Majestic PAC II"},
  "/capuchas/romak-cap1005/": {"title": "Monja para bombero Romak Fire CAP1005 over-face", "description": "Monja para bombero Romak Fire CAP1005 over-face: material, capas, apertura facial y cuidado para validar la interfaz con ERA, casco y chaquetón.", "h1": "Monja para bombero Romak Fire CAP1005 over-face"},
  "/capuchas/skold-fpen/": {"title": "Escafandra Nomex Sköld FPEN: monja para bombero", "description": "Escafandra Nomex Sköld FPEN para bombero: material, capas, apertura facial y cuidado para validar la interfaz con ERA, casco y chaquetón. Cotiza.", "h1": "Escafandra Nomex Sköld FPEN para bombero"},
  "/accesorios/lampara-de-casco/": {"title": "Lámpara de casco para bombero con manos libres", "description": "Lámpara de casco para bombero: deja las manos libres y debe apuntar sin estorbar visor, máscara ni retención. Compatibilidad con tu casco al cotizar."},
  "/accesorios/linterna-de-bombero/": {"title": "Linterna de bombero para uso con guante estructural", "description": "Linterna de bombero: se elige por agarre, interruptor, energía y forma de llevarla con guante en la escena. Revisa la ficha técnica y cotiza la partida."},
  "/accesorios/goggles/": {"title": "Goggles para bombero forestal y de rescate", "description": "Goggles para bombero: lente, marco y correa que conservan la visión en una exposición definida, forestal o de rescate. Compatibilidad con el casco al cotizar."},
  "/accesorios/camara-termica/": {"title": "Cámara térmica para bomberos: búsqueda y ataque", "description": "Cámara térmica para bomberos: muestra contrastes de radiación infrarroja y exige entrenamiento para leerlos en la escena. Cotiza con ficha técnica."},
  "/accesorios/dispositivo-pass/": {"title": "Dispositivo PASS para bombero: alarma personal", "description": "Dispositivo PASS para bombero: alerta personal de inmovilidad dentro de una respuesta institucional que debe estar ensayada. Cotiza con ficha técnica."},
  "/accesorios/maleta-porta-equipo/": {"title": "Maleta porta-equipo para bombero y traje completo", "description": "Maleta porta-equipo para bombero: organiza el traslado del conjunto y se valida cargando casco, botas, prendas y accesorios reales. Cotiza con ficha técnica."},
  "/accesorios/streamlight-vantage/": {"title": "Lámpara de casco Streamlight Vantage para bombero", "description": "Lámpara de casco Streamlight Vantage para bombero: LED C4, giro de 360°, clip para el ala del casco y dos CR123A incluidas. Compatibilidad al cotizar.", "h1": "Lámpara de casco Streamlight Vantage para bombero"},
  "/accesorios/ess-striketeam-xto/": {"title": "Goggles ESS Striketeam XTO para bombero forestal", "description": "Goggles ESS Striketeam XTO para bombero forestal: Speed-Clip, ventilación perimetral, lente intercambiable y normas declaradas por el fabricante. Cotízalos.", "h1": "Goggles ESS Striketeam XTO para bombero forestal"},
  "/accesorios/romak-bps1005/": {"title": "Maleta porta-equipo Romak Fire BPS1005 para bombero", "description": "Maleta porta-equipo Romak Fire BPS1005 en poliéster repelente al agua para trasladar el conjunto del bombero: casco, botas, prendas y accesorios.", "h1": "Maleta porta-equipo Romak Fire BPS1005 para bombero"},
  "/herramientas/hacha-de-bombero/": {"title": "Hacha de bombero para acceso y entrada forzada", "description": "Hacha de bombero para acceso y entrada forzada: corte y golpe en una pieza. Define cabeza, mango, peso declarado y resguardo antes de cotizar la partida.", "h1": "Hacha de bombero para acceso y entrada forzada", "lead": "El hacha para bombero combina corte y golpe en maniobras autorizadas de acceso y entrada forzada. Define cabeza, mango, peso y resguardo según la operación.", "faqsExtra": [{"q": "¿Para qué sirve el hacha de bombero?", "a": "Combina corte y golpe para maniobras autorizadas de acceso, entrada forzada y retiro de material. Se elige por el tipo de cabeza, el material y largo del mango y el peso, y se resguarda en la unidad dentro de un programa de mantenimiento."}, {"q": "¿Cuánto pesa un hacha de bombero?", "a": "El peso depende del modelo, de la cabeza y del mango. Esta ficha no publica un modelo ni un peso único, por lo que no sería correcto dar una cifra general. Al cotizar, pide el peso declarado, largo, tipo de cabeza y método de resguardo para compararlos con tu maniobra."}]},
  "/herramientas/barra-halligan/": {"title": "Herramienta Halligan para bombero y entrada forzada", "description": "Herramienta Halligan para bombero: entrada forzada, largo, material, mantenimiento y resguardo. Solicita la ficha técnica para cotizar.", "h1": "Herramienta Halligan para bombero y entrada forzada", "lead": "La herramienta Halligan para bombero sirve en entrada forzada y rescate. Define largo, material, garra y resguardo con base en las maniobras autorizadas de tu corporación.", "faqsExtra": [{"q": "¿Qué significa Halligan?", "a": "Halligan es el nombre de una barra de entrada forzada usada por bomberos. Combina una garra, una cuña y una punta para aplicar palanca, separar elementos o crear acceso. No sustituye la capacitación: su uso se define por la maniobra, la escena y el procedimiento de la corporación."}, {"q": "¿Para qué se utiliza un Halligan?", "a": "Se utiliza en entrada forzada para aplicar palanca y crear acceso cuando la maniobra está autorizada. También puede apoyar trabajos de rescate según la técnica entrenada. La compra debe definir largo, material y configuración, además del método de resguardo seguro en la unidad."}]},
  "/herramientas/gancho-bichero/": {"title": "Gancho bichero para bombero: alcance y remoción", "description": "Gancho bichero para bombero: alcanzar, jalar o revisar desde una posición segura; largo, cabezal, control, mantenimiento y datos para cotizar la partida."},
  "/herramientas/pulaski/": {"title": "Pulaski: herramienta forestal de hacha y azadón", "description": "Pulaski para bombero forestal: hacha y azadón en una sola cabeza para brecha y línea de control. Selección, mango, afilado, resguardo y datos para cotizar.", "h1": "Pulaski: herramienta forestal para bombero"},
  "/herramientas/mcleod/": {"title": "McLeod: herramienta forestal de rastrillo y azadón", "description": "McLeod para bombero forestal: rastrillo y azadón para raspar la línea de control hasta suelo mineral. Define pala, mango y mantenimiento y cotiza.", "h1": "McLeod: herramienta forestal para bombero", "faqsExtra": [{"q": "¿Qué es un McLeod?", "a": "El McLeod es una herramienta forestal que combina rastrillo y azadón en una misma cabeza. Sirve para raspar combustible y trabajar la línea de control hasta suelo mineral. Se selecciona por la forma de la pala, el mango y el uso que realizará la brigada en campo."}, {"q": "¿Qué significa McLeod en herramientas forestales?", "a": "En el contexto forestal, McLeod nombra una herramienta de doble función, con dientes de rastrillo por un lado y filo de azadón por el otro. No describe un tipo de rastrillo de jardín. Su mantenimiento incluye limpiar la cabeza, revisar el mango y resguardarla correctamente."}]},
  "/herramientas/batefuego/": {"title": "Batefuego para combate de incendio forestal", "description": "Batefuego para bombero forestal: sofocar fuego de pasto y material ligero; paleta, mango, peso, mantenimiento y resguardo. Datos para cotizar la partida.", "h1": "Batefuego: herramienta forestal para bombero"},
  "/herramientas/rastrillo-forestal/": {"title": "Rastrillo forestal con mango para bombero y brigada", "description": "Rastrillo forestal con mango para limpiar combustible ligero en la línea de control. Define dientes, mango y mantenimiento antes de cotizar.", "h1": "Rastrillo forestal con mango para bombero", "lead": "El rastrillo forestal con mango retira combustible ligero en la línea de control. Revisa dientes, pala, mango y resguardo según el terreno y la tarea de la brigada.", "faqsExtra": [{"q": "¿Qué es un rastrillo forestal y para qué se utiliza?", "a": "Es una herramienta de brigada para retirar combustible ligero y apoyar la construcción de una línea de control en incendio forestal. No se selecciona como un rastrillo de jardinería. La pala, los dientes y el mango deben corresponder al terreno y a la técnica que practica tu equipo."}, {"q": "¿Qué características tiene un rastrillo forestal?", "a": "La ficha debe describir forma y material de la pala, cantidad y disposición de dientes, tipo y longitud de mango y método de resguardo. Estos datos determinan cómo mueve combustible ligero y cómo se transporta. Te confirmamos cada dato con la ficha del fabricante antes de cotizar."}]},
  "/herramientas/bomba-de-mochila-forestal/": {"title": "Bomba de mochila forestal para incendio de vegetación", "description": "Bomba de mochila forestal para bombero: agua para apoyo puntual en vegetación; capacidad, arnés y mantenimiento que la hacen confiable. Datos para cotizar."},
  "/herramientas/romak-hac1007/": {"title": "Barra Halligan Romak Fire HAC1007 de acero inoxidable", "description": "Barra Halligan Romak Fire HAC1007 de acero inoxidable, 91 cm y 6 lb, para rescate y entrada forzada. Consulta configuración y cotiza con ficha técnica.", "h1": "Barra Halligan Romak Fire HAC1007 para bombero"},
  "/rescate/herramienta-hidraulica-de-rescate/": {"title": "Quijadas de la vida: equipo hidráulico de rescate", "description": "Quijadas de la vida y equipo hidráulico para extricación: separador, cortador y cilindro. Define el sistema y cotiza con ficha técnica.", "h1": "Equipo hidráulico de rescate y quijadas de la vida", "lead": "Las quijadas de la vida son equipo hidráulico de rescate para extricación de personas atrapadas. Separador, cortador, combinada y cilindro cumplen maniobras distintas dentro del sistema.", "faqsExtra": [{"q": "¿Qué son las quijadas de la vida?", "a": "Es el nombre con el que se conoce a la herramienta hidráulica de rescate. Incluye separadores, cortadores, herramientas combinadas y cilindros que abren, cortan o empujan la estructura de un vehículo para liberar a una persona atrapada. Cada pieza trabaja con el sistema de potencia que declara su fabricante."}, {"q": "¿Cómo funcionan las quijadas de la vida?", "a": "Funcionan mediante un sistema hidráulico o de batería, según el equipo seleccionado. El separador abre y crea espacio, el cortador trabaja postes y perfiles, y el cilindro empuja. La maniobra inicia tras estabilizar el vehículo y controlar la escena, siempre con personal entrenado."}]},
  "/rescate/arnes-de-rescate/": {"title": "Arnés de rescate para bomberos y trabajo en altura", "description": "Arnés de rescate y seguridad para trabajo en altura: clases, anclajes, talla e inspección. Revisa la maniobra y cotiza con ficha técnica.", "h1": "Arnés de rescate para trabajo en altura", "lead": "El arnés de rescate es un arnés de cuerpo completo para maniobras con cuerda y trabajo en altura. Se elige por clase, talla, anclajes y compatibilidad con el sistema.", "faqsExtra": [{"q": "¿Qué es un arnés de rescate?", "a": "Es un arnés de cuerpo completo que une al rescatista con un sistema de cuerda durante acceso, descenso, ascenso o posicionamiento. Se diferencia de un arnés industrial de protección contra caídas porque la clase y los puntos de conexión deben corresponder a la maniobra de rescate."}, {"q": "¿Qué dice la norma ANSI Z359?", "a": "ANSI Z359 es una referencia industrial para sistemas de protección contra caídas. En bomberos, la ficha usa NFPA 2500 como referencia para equipo de rescate con cuerda. Ninguna norma sustituye revisar lo que declara el modelo, su clase, sus anclajes y la compatibilidad con la línea de vida."}, {"q": "¿Cuáles son los tipos de arneses de seguridad?", "a": "Por su uso se distinguen el cinturón o arnés de cintura, para posicionamiento o escape; el arnés de asiento, con perneras, para rescate de una persona; y el arnés de cuerpo completo, con correas en torso y piernas, que reparte la carga en una suspensión o una caída. En trabajos en altura industriales, el anticaída lleva anillo D dorsal. En rescate, la clase la define la maniobra."}, {"q": "¿Qué es el trauma por suspensión?", "a": "Es la condición que aparece cuando una persona queda colgada del arnés sin moverse: las correas de las perneras comprimen las piernas y la sangre deja de regresar bien al corazón. Por eso el rescate de un trabajador suspendido en altura o en un espacio confinado debe ser rápido y planeado, con equipo de rescate listo antes de empezar el trabajo."}]},
  "/rescate/cuerda-de-rescate/": {"title": "Cuerda de rescate estática para trabajo en altura", "description": "Cuerda de rescate estática kernmantle para trabajo en altura: diámetro, longitud e inspección. Define la función y cotiza con ficha técnica.", "h1": "Cuerda de rescate estática para trabajo en altura", "lead": "La cuerda de rescate estática kernmantle se usa en trabajo en altura y rescate vertical. Se define por diámetro, longitud, terminaciones y compatibilidad con el sistema.", "faqsExtra": [{"q": "¿Qué es una cuerda de rescate?", "a": "Es una cuerda usada dentro de un sistema de rescate para descenso, ascenso, izado o aseguramiento. Esta ficha aborda cuerda estática tipo kernmantle, cuya construcción combina núcleo portante y funda protectora. Se selecciona por diámetro, longitud y compatibilidad con descensores, conectores y anclajes."}, {"q": "¿Qué tipos de cuerdas de rescate existen?", "a": "Para rescate con cuerda se distinguen por su función dentro del sistema, como línea principal, respaldo o acceso. Esta página se refiere a cuerda estática kernmantle. La cuerda dinámica de escalada se estira para absorber caídas y no se debe intercambiar sin revisar el procedimiento y el equipo."}]},
  "/rescate/mosquetones-de-rescate/": {"title": "Mosquetones de seguridad para rescate de bomberos", "description": "Mosquetones de seguridad para rescate: acero o aluminio, seguro automático o de rosca, resistencia marcada y compatibilidad del sistema. Cotiza con ficha.", "lead": "Los mosquetones de seguridad para rescate se comparan por material, tipo de seguro, forma y resistencia marcada por el fabricante para el sistema donde se emplearán.", "faqsExtra": [{"q": "¿Qué tipos de mosquetones de seguridad hay para rescate?", "a": "Se distinguen por material (acero o aluminio), por seguro (de rosca o automático) y por forma (en D, D asimétrico u oval). En rescate se eligen por la resistencia marcada en el cuerpo del mosquetón y por su compatibilidad con cuerda, placa y polea; un mosquetón de llavero o decorativo no sirve para cargar personas."}]},
  "/rescate/kit-de-rescate-vertical/": {"title": "Kit de rescate vertical para bomberos con cuerda y arnés", "description": "Kit de rescate vertical para bomberos con cuerda, arnés, descensor, poleas y anclajes compatibles. Define la técnica de rescate y cotiza con ficha técnica.", "h1": "Kit de rescate vertical y técnicas de rescate", "lead": "El kit de rescate vertical reúne cuerda, arnés, descensor, poleas y anclajes para una técnica de rescate definida. La seguridad depende de que todos los componentes sean compatibles.", "faqsExtra": [{"q": "¿Qué significa rescate vertical?", "a": "Rescate vertical es el conjunto de técnicas para acceder, descender, ascender, asegurar o recuperar personas mediante sistemas de cuerda. Puede realizarse en altura, desniveles o espacios donde no hay acceso directo. El kit se configura por escenario, maniobra, número de usuarios y compatibilidad entre sus componentes."}, {"q": "¿Qué tipos de rescate en altura existen?", "a": "Las maniobras pueden incluir acceso por cuerda, descenso, ascenso, izado y evacuación horizontal asistida. La técnica correcta depende del escenario y del entrenamiento del equipo. No conviene comprar un kit genérico: define primero las técnicas que practica tu corporación y pide la ficha de cada componente."}]},
  "/mangueras-y-accesorios/manguera-de-ataque/": {"title": "Manguera de bombero de ataque contra incendio", "description": "Manguera de bombero de ataque contra incendio de 1 ½ o 2 ½ pulgadas, con acoples y doble chaqueta según configuración. Cotiza con ficha técnica.", "h1": "Manguera de bombero de ataque contra incendio", "lead": "La manguera de bombero de ataque conduce agua de la bomba al pitón. Se selecciona por diámetro, longitud, doble chaqueta, acoples y rosca compatibles con la línea.", "faqsExtra": [{"q": "¿Cómo se llama la manguera que utilizan los bomberos?", "a": "La línea que lleva agua al pitón se conoce como manguera de ataque. Se pide por diámetro, longitud, construcción, acoples y rosca. Esta ficha contempla 1 ½ y 2 ½ pulgadas, con doble chaqueta según la configuración; el modelo final debe confirmar los datos técnicos."}, {"q": "¿Qué características hay que considerar al elegir una manguera de bombero?", "a": "Revisa el diámetro, la longitud de cada tramo, la construcción, los acoples y la rosca que ya usa tu bomba y tu pitón. También confirma el uso de la línea y la norma que declare el fabricante. No mezcles medidas o roscas sin adaptadores previstos."}]},
  "/mangueras-y-accesorios/piton-boquilla/": {"title": "Chiflón para manguera contra incendio: pitón o boquilla", "description": "Chiflón para manguera contra incendio: pitón o boquilla de chorro y niebla, caudal, conexión y mantenimiento. Datos para cotizar la partida con ficha.", "h1": "Chiflón, pitón o boquilla para manguera contra incendio", "lead": "El chiflón para manguera contra incendio, también llamado pitón o boquilla, se selecciona por patrón de chorro o niebla, caudal declarado y acople compatible con la manguera y la maniobra.", "faqsExtra": [{"q": "¿Qué es un chiflón para manguera contra incendio?", "a": "Es la boquilla que va al final de la manguera y controla la descarga: abre, cierra y define el patrón de chorro directo, niebla o combinado. En México se le llama chiflón, pitón o boquilla; se elige por caudal declarado, presión de trabajo y el acople de la manguera."}, {"q": "¿Sirve un chiflón de jardín para una manguera contra incendio?", "a": "No. Un chiflón de jardín no está construido para la presión, el caudal ni los acoples de una línea contra incendio. Para gabinete, hidrante o autobomba se especifica un pitón contra incendio con su ficha técnica y el diámetro de la manguera."}]},
  "/mangueras-y-accesorios/llave-para-hidrante/": {"title": "Llave para hidrante contra incendio y llaves spanner", "description": "Llave para hidrante contra incendio y llaves spanner: tipo de operación, tamaño de conexiones y compatibilidad con los elementos instalados. Cotiza con ficha."},
  "/mangueras-y-accesorios/conexiones-y-adaptadores/": {"title": "Conexiones y adaptadores para manguera contra incendio", "description": "Conexiones y adaptadores contra incendio: reducciones, siamesas y adaptadores por rosca, diámetro y flujo requerido, sin asumir equivalencias. Cotiza."},
  "/kits/kit-estructural/": {"title": "Kit de bombero estructural: traje, casco, botas y guantes", "description": "Kit de bombero estructural con traje, casco, monja, guantes y botas para revisar cobertura, tallas e interfaz en una sola partida. Cotiza con ficha técnica."},
  "/kits/kit-brigadista/": {"title": "Kit de brigadista contra incendio NOM-002-STPS", "description": "Kit brigadista contra incendio con traje, casco, capucha, guantes y botas para definir una partida conforme al riesgo y procedimiento del centro de trabajo."},
  "/kits/kit-forestal/": {"title": "Kit forestal para brigada y bombero de línea de fuego", "description": "Kit forestal con ropa, casco, goggles, guantes, bota y nuquera para armar la protección de línea de fuego según la tarea de la cuadrilla. Cotiza con ficha."},
  "/marcas/": {"title": "Marcas de equipo para bombero: Romak Fire y Sköld", "description": "Marcas de equipo para bombero que cotizamos: Romak Fire y Sköld, con trajes, cascos, botas, guantes y ERA configurados según cada operación."},
  "/marcas/romak-fire/": {"title": "Romak Fire: trajes para bombero y equipo contra incendio", "description": "Romak Fire: trajes para bombero estructurales, de brigadista, forestales y de aproximación, más botas, guantes y herramientas. Consulta modelos y cotiza.", "h1": "Romak Fire: trajes y equipo para bombero"},
  "/marcas/skold/": {"title": "Sköld: trajes, cascos, botas y ERA para bombero", "description": "Sköld: trajes, casco, bota, guantes, escafandra y ERA para bombero. Revisa los modelos publicados, su estatus normativo y su documentación al cotizar.", "h1": "Sköld: trajes y equipo para bombero"},
};

export const metaSeo = (path: string): MetaSeo | undefined => METAS_SEO[path];

// Complementos editoriales específicos por ficha. Conservan los metadatos originales.
const COMPLEMENTOS_4B1: Record<string, Pick<MetaSeo, 'lead' | 'faqsExtra'>> = {
  '/cascos/casco-forestal/': { lead: 'En un casco forestal, revisa antes de asignarlo que la suspensión no gire, que el barbiquejo cierre con guantes y que goggles o linterna no bloqueen la ventilación. Esta pieza acompaña el trabajo prolongado en línea de fuego.', faqsExtra: [{ q: '¿Qué reviso en un casco forestal antes de una guardia?', a: 'Revisa la carcasa, suspensión, barbiquejo, nuquera y los accesorios montados. El casco debe asentarse sin moverse al inclinar la cabeza. Si integra goggles o linterna, confirma que no interfieran con el ajuste ni con el campo de visión.' }] },
  '/botas/bota-forestal/': { lead: 'La bota forestal se prueba caminando, subiendo y bajando terreno irregular. Revisa agujetas, ojillos, unión de la suela y apoyo del tobillo antes de integrarla con pantalón, polainas y el resto del calzado de protección.', faqsExtra: [{ q: '¿Cómo pruebo una bota forestal antes de asignarla?', a: 'Póntela con el calcetín de servicio y camina en pendiente, flexiona el tobillo y revisa que las agujetas mantengan el ajuste. Confirma que la suela tenga agarre y que no haya separaciones, cortes o desgaste que comprometan el uso en incendio forestal.' }] },
  '/guantes/guante-estructural/': { lead: 'El guante estructural se inspecciona por dentro y por fuera. Voltea el puño para revisar costuras, confirma que la barrera no esté separada y pruébalo con la manga del chaquetón y la herramienta que usas en incendio.', faqsExtra: [{ q: '¿Qué señales obligan a retirar un guante estructural?', a: 'Retíralo si tiene costuras abiertas, palma endurecida, quemaduras, perforaciones o una barrera desplazada. También revisa cada dedo desde el interior. Un guante de bombero debe conservar movilidad y solapar con la manga para proteger la muñeca.' }] },
  '/botas/bota-de-brigada-industrial/': { lead: 'Esta bota para brigada industrial se define por las tareas autorizadas del centro de trabajo. Al recibirla, revisa talla, cierre, suela y condición de la puntera, luego úsala con el uniforme y las rutas de evacuación previstas.', faqsExtra: [{ q: '¿Qué debe confirmar una brigada al recibir botas industriales?', a: 'La brigada debe comprobar talla individual, integridad de suela y corte, cierre funcional y datos de la ficha del modelo. La bota no sustituye el análisis de riesgo. Su uso se integra al procedimiento de la brigada y a NOM-002-STPS-2010.' }] },
  '/botas/bota-de-hule-estructural/': { lead: 'En una bota de hule estructural, revisa el cuerpo completo antes del servicio. Busca cortes, ampollas, grietas y desprendimientos en la suela, y confirma que el pantalón del traje cubra correctamente la parte superior de la bota.', faqsExtra: [{ q: '¿Cómo se inspecciona una bota de hule estructural?', a: 'Limpia la bota y revisa el hule desde la caña hasta la suela. Busca grietas, perforaciones, deformación por calor y separación en la unión. Prueba el ajuste con el pantalón estructural para evitar huecos durante una maniobra de incendio.' }] },
  '/botas/bota-de-piel-estructural/': { lead: 'La bota de piel estructural necesita secado controlado después de la intervención. Retira la humedad según las indicaciones del fabricante, revisa costuras y conserva la forma de la caña antes de usarla otra vez con el traje.', faqsExtra: [{ q: '¿Cómo cuido una bota de piel estructural después de usarla?', a: 'Quita suciedad y humedad conforme a la ficha del fabricante. No la seques sobre una fuente directa de calor, porque puede afectar la piel, adhesivos y suela. Antes de volver al servicio, revisa costuras, caña, agujetas y el estado del calzado.' }] },
  '/botas/croydon-filtrex/': { lead: 'Para recibir la Croydon Filtrex, coteja el código, talla y configuración de la orden con su ficha. Luego revisa que la suela esté limpia y que el usuario pueda subir escalones y mantener equilibrio sin puntos de presión.', faqsExtra: [{ q: '¿Qué se coteja al recibir una Croydon Filtrex?', a: 'Coteja código, talla, cantidad y configuración contra la orden y la ficha técnica publicada. Después prueba ambos pies con el calcetín de servicio. Revisa suela, caña y forro, y registra cualquier diferencia antes de asignar la bota al bombero.' }] },
  '/botas/romak-fire-ranger-bota/': { lead: 'La Romak Fire Ranger se revisa como bota forestal de agujetas antes de cada salida. Comprueba tensión pareja, estado de la piel y limpieza de la suela para que el apoyo sea consistente al trabajar sobre terreno suelto.', faqsExtra: [{ q: '¿Cómo ajusto una Romak Fire Ranger para trabajo forestal?', a: 'Ajusta las agujetas desde el empeine hasta la caña sin dejar zonas flojas ni cortar la circulación. Camina y flexiona el tobillo antes de salir. Revisa que la suela no retenga lodo o piedras, porque cambian el agarre en terreno irregular.' }] },
  '/botas/romak-workman-fire/': { lead: 'Antes de asignar una Romak Workman Fire, revisa el hule, forro, plantilla y suela de cada pie. La prueba útil incluye subir un escalón, agacharse y comprobar que el pantalón estructural cubra la caña sin atorarse.', faqsExtra: [{ q: '¿Qué prueba funcional hago con la Romak Workman Fire?', a: 'Haz la prueba con el conjunto que usará la persona. Camina, sube un escalón, agáchate y revisa la cobertura entre pantalón y bota. Después revisa que no haya grietas, residuos dentro del calzado ni daños en la suela.' }] },
  '/botas/skold-workman/': { lead: 'La Sköld Workman requiere una inspección limpia y visual al inicio de cada turno. Revisa la caña, el borde superior y la huella de la suela; después confirma que el ajuste permita operar pedales y subir a la unidad.', faqsExtra: [{ q: '¿Qué partes debo revisar en una Sköld Workman?', a: 'Revisa la caña, borde superior, forro, plantilla y toda la suela. Busca grietas, deformación, desgaste irregular o contaminación que no se haya retirado. La prueba debe incluir movilidad de tobillo y control al subir y bajar de la unidad.' }] },
  '/botas/strongfire-bota-forestal/': { lead: 'La Strong Fire se prepara para jornada forestal revisando agujetas, piel y apoyo del tobillo. Después de cada salida, elimina tierra y vegetación de la suela para detectar desgaste, cortes o costuras que requieran atención.', faqsExtra: [{ q: '¿Cómo mantengo una Strong Fire entre jornadas forestales?', a: 'Retira tierra y combustible vegetal con un cepillo suave y deja secar la bota en un sitio ventilado. Revisa agujetas, piel, costuras y suela antes de guardarla. Si notas cortes profundos o separación, aparta el par para evaluación.' }] },
  '/capuchas/majestic-pac-ii/': { lead: 'La Majestic PAC II se coloca después de revisar que la tela vuelva a su forma y que no tenga perforaciones. En la prueba con ERA, acomoda la apertura para que la máscara selle sobre la piel y el casco cubra la monja.', faqsExtra: [{ q: '¿Cómo compruebo el sello con una Majestic PAC II?', a: 'Ponte la monja, coloca la máscara directamente sobre la piel y realiza la prueba de sello indicada para el ERA. Después ajusta casco y chaquetón. La tela no debe quedar dentro del sello ni formar huecos en cuello, orejas o mandíbula.' }] },
  '/capuchas/romak-cap1005/': { lead: 'La Romak Fire CAP1005 se revisa por su apertura facial y por el tejido de cabeza, cuello y hombros. En la prueba de conjunto, confirma que la máscara selle en la piel y que el casco no desplace la capucha.', faqsExtra: [{ q: '¿Qué reviso en la apertura facial de una CAP1005?', a: 'Revisa que la apertura quede limpia, sin deformación ni fibras sueltas. Al colocar la máscara de ERA, el sello debe apoyar directamente sobre la piel. Después mueve cabeza y brazos con casco y chaquetón para comprobar que no se formen huecos.' }] },
  '/capuchas/skold-fpen/': { lead: 'La escafandra Sköld FPEN se revisa estirando con suavidad la apertura y observando sus capas. Úsala con máscara, casco y chaquetón para revisar cobertura continua de cuello y hombros sin introducir tela en el sello.', faqsExtra: [{ q: '¿Cómo inspecciono una escafandra Sköld FPEN?', a: 'Busca perforaciones, desgaste, costuras abiertas y pérdida de elasticidad alrededor de la apertura facial. La inspección termina con una prueba de conjunto. La máscara debe sellar sobre la piel y el casco debe conservar la cobertura al mover la cabeza.' }] },
  '/cascos/bullard-fh911h/': { lead: 'El Bullard FH911H se inspecciona con atención en ala, suspensión y barbiquejo. Antes de una salida forestal, comprueba que el casco quede estable al mirar hacia abajo y que sus accesorios previstos no cambien su ajuste.', faqsExtra: [{ q: '¿Qué reviso primero en un Bullard FH911H?', a: 'Revisa la carcasa y el ala por golpes o grietas, después la suspensión y el barbiquejo. Ajusta el casco y mueve la cabeza en varias direcciones. Si incorpora accesorios, confirma que estén previstos para el modelo y no interfieran con el ajuste.' }] },
  '/cascos/casco-brigada-industrial/': { lead: 'El casco de brigada industrial se recibe contra el riesgo definido en el centro de trabajo. Revisa ajuste, retención y accesorios antes de asignarlo, y confirma que la configuración coincida con las maniobras autorizadas para tu brigada.', faqsExtra: [{ q: '¿Cómo elijo un casco para brigada industrial?', a: 'Parte del análisis de riesgo y las tareas autorizadas. Define si se requiere protección ocular, comunicación o accesorios específicos y valida su compatibilidad. El casco debe ajustarse al usuario y formar parte del programa de brigada previsto por NOM-002-STPS-2010.' }] },
  '/cascos/casco-estructural-europeo/': { lead: 'En un casco estructural europeo, prueba primero visor, retención y máscara de ERA como conjunto. Revisa que el perfil de nuca no choque con el cuello del chaquetón y que las comunicaciones, si se requieren, estén previstas por el fabricante.', faqsExtra: [{ q: '¿Qué pruebo junto con un casco estructural europeo?', a: 'Prueba máscara de ERA, monja, visor y chaquetón al mismo tiempo. Mueve la cabeza, levanta los brazos y confirma que el casco no desplace el sello de la máscara. También revisa que la retención y los accesorios estén contemplados en la configuración.' }] },
  '/cascos/casco-estructural-tradicional/': { lead: 'El casco estructural tradicional se revisa con sus cinco piezas operativas: carcasa, suspensión, barbiquejo, cubrenuca y visor. La prueba debe hacerse con máscara, monja y chaquetón para identificar cualquier hueco o interferencia antes de servicio.', faqsExtra: [{ q: '¿Por qué debo probar el casco tradicional con el ERA?', a: 'Porque la máscara, monja, visor y casco forman una interfaz. Un casco que desplaza la máscara puede afectar el sello y uno que gira compromete la visión. La prueba de ajuste con todo el conjunto descubre esas interferencias antes de una emergencia.' }] },
  '/cascos/casco-rescate-tecnico/': { lead: 'El casco de rescate técnico se revisa con la maniobra que realizará el equipo. Prueba barbiquejo, ajuste y accesorios con goggles, lámpara o comunicación, y confirma que no generen puntos de enganche en vehículos, cuerdas o espacios reducidos.', faqsExtra: [{ q: '¿Qué diferencia la revisión de un casco de rescate técnico?', a: 'La revisión se centra en retención, cobertura y compatibilidad con los accesorios de la maniobra. Prueba la lámpara, goggles o comunicación antes de asignarlos. El casco debe permanecer estable al agacharte, girar y trabajar cerca de cuerdas o estructuras.' }] },
  '/cascos/skold-viking/': { lead: 'El Sköld Viking se debe probar con la protección ocular y el ERA que ya usa tu corporación. Revisa que el barbiquejo cierre de forma uniforme y que el casco no rote cuando el usuario eleva la vista o se inclina.', faqsExtra: [{ q: '¿Cómo confirmo el ajuste de un Sköld Viking?', a: 'Colócalo con monja y máscara de ERA. Ajusta la suspensión y el barbiquejo, luego gira e inclina la cabeza. El casco debe permanecer centrado, sin desplazar la máscara ni limitar la visión. Revisa también el estado del visor antes de guardia.' }] },
  '/equipo-de-respiracion-autonoma/cilindros-de-fibra-de-carbono/': { lead: 'Un cilindro de fibra de carbono se revisa por etiqueta, válvula, conexión y superficie externa antes de montarlo en la espaldera. Nunca se mezcla con un ERA distinto sin confirmar compatibilidad, presión de carga y procedimiento del fabricante.', faqsExtra: [{ q: '¿Qué datos reviso en un cilindro de fibra de carbono para ERA?', a: 'Revisa la etiqueta, identificación, condición de la válvula, conexión y el estado de la superficie. Confirma que sea compatible con la espaldera y el sistema de carga. Si hay golpe, daño, fuga o duda sobre su inspección, retíralo del servicio.' }] },
  '/equipo-de-respiracion-autonoma/era-de-combate/': { lead: 'El ERA de combate se prueba como sistema antes de entrar a una atmósfera peligrosa. Revisa presión, válvula, manómetro, regulador, máscara, alarma y conexión del cilindro; después confirma el sello con casco, monja y guantes puestos.', faqsExtra: [{ q: '¿Cuál es la revisión previa de un ERA de combate?', a: 'Comprueba presión disponible, válvula, manómetro, regulador, alarma y la conexión del cilindro. Coloca la máscara y realiza la prueba de sello establecida por el fabricante. El conjunto incluye casco, monja y guantes, porque todos pueden afectar la operación.' }] },
  '/equipo-de-respiracion-autonoma/era-de-escape/': { lead: 'El ERA de escape se mantiene listo para evacuar, no para intervenir. Revisa indicador, sellos, correa y acceso rápido antes de entrar a una zona de riesgo, y capacita al usuario en la ruta de salida y el procedimiento aplicable.', faqsExtra: [{ q: '¿Cuándo se usa un ERA de escape?', a: 'Se usa para evacuar una atmósfera peligrosa cuando el procedimiento lo contempla. No sustituye un equipo de respiración autónoma para combate ni un sistema de rescate planeado. El usuario debe conocer su activación, ajuste y la ruta de salida antes de requerirlo.' }] },
  '/equipo-de-respiracion-autonoma/era-industrial/': { lead: 'El ERA industrial se verifica junto con el análisis de atmósfera y el procedimiento de la instalación. Antes de uso, revisa máscara, regulador, cilindro, manómetro y alarmas, y confirma que el personal tenga entrenamiento para la tarea autorizada.', faqsExtra: [{ q: '¿Qué confirma una inspección de ERA industrial?', a: 'Confirma presión, válvulas, conexiones, máscara, regulador, arnés y alarmas según la ficha del equipo. También verifica que la aplicación coincida con el programa de protección respiratoria de la instalación. Un ERA industrial no se asigna como sustituto de uno de combate.' }] },
  '/equipo-de-respiracion-autonoma/mascaras-y-reguladores-era/': { lead: 'Las máscaras y reguladores de ERA se inspeccionan como una interfaz crítica. Revisa mica, sello facial, válvulas, conectores y respuesta del regulador; después realiza la prueba de sello sin interponer cabello, barba o tela de la monja.', faqsExtra: [{ q: '¿Por qué una máscara de ERA no debe sellar sobre la monja?', a: 'La máscara necesita apoyar sobre la piel para mantener el sello facial. La tela puede crear una vía de fuga. Revisa que la monja cubra alrededor de la máscara y que el regulador conecte y desconecte conforme al procedimiento del fabricante.' }] },
  '/equipo-de-respiracion-autonoma/msa-g1-industrial/': { lead: 'El MSA G1 Industrial se recibe cotejando código y configuración con su ficha. Antes de asignarlo, prueba máscara, regulador, arnés, cilindro y alarmas como un sistema, dentro del programa de protección respiratoria de la instalación.', faqsExtra: [{ q: '¿Qué debo cotejar al recibir un MSA G1 Industrial?', a: 'Coteja el código, la configuración y los componentes incluidos contra la orden y ficha técnica. Realiza después la revisión funcional de máscara, regulador, manómetro, arnés y cilindro. La asignación requiere capacitación y el procedimiento industrial aplicable.' }] },
  '/equipo-de-respiracion-autonoma/skold-phantom/': { lead: 'El Sköld Phantöm se inspecciona antes de guardia desde el cilindro hasta la máscara. Verifica presión, válvula, manómetro, reguladores, arnés y alarmas, y realiza la prueba de sello con la monja y casco que se usarán en operación.', faqsExtra: [{ q: '¿Qué incluye la prueba previa de un Sköld Phantöm?', a: 'Incluye revisar cilindro, válvula, presión, manómetro, reguladores, máscara, arnés y alarmas. Después el usuario se coloca monja y casco para confirmar que la máscara conserve su sello. Cualquier fuga, golpe o alarma irregular exige apartar la unidad.' }] },
  '/guantes/guante-brigadista/': { lead: 'El guante brigadista se selecciona según la tarea autorizada, no como sustituto automático del guante estructural. Antes de asignarlo, prueba destreza, ajuste y agarre con extintor, manguera o herramienta, y revisa palma y costuras.', faqsExtra: [{ q: '¿Un guante brigadista sustituye a un guante estructural?', a: 'No necesariamente. El guante se elige por la exposición y la tarea. Para una brigada, prueba el modelo con extintor, manguera o herramienta. Si la operación exige incendio estructural, el equipo debe corresponder al riesgo y procedimiento definidos.' }] },
  '/guantes/guante-forestal/': { lead: 'El guante forestal debe permitir sujetar herramienta manual durante una jornada sin perder control. Revisa palma, dedos, costuras y cierre; después pruébalo con Pulaski, McLeod o rastrillo antes de incorporarlo al equipo de línea.', faqsExtra: [{ q: '¿Cómo pruebo un guante forestal con herramienta manual?', a: 'Póntelo y prueba agarre, apertura de mano y movilidad de dedos con la herramienta de línea que usará la brigada. Revisa que no haya costuras que rocen ni desgaste en la palma. Después de uso, limpia tierra y revisa cortes o abrasión.' }] },
  '/guantes/guante-rescate-extricacion/': { lead: 'El guante de rescate y extricación se prueba con los objetos que exige la maniobra: vidrio, lámina controlada, eslingas, mosquetones y controles. Revisa palma, dedos y cierre después de cada servicio para detectar cortes o contaminación.', faqsExtra: [{ q: '¿Qué maniobras debo probar con un guante de extricación?', a: 'Prueba abrir un mosquetón, manejar una eslinga, operar controles y sujetar una herramienta sin perder destreza. Revisa la palma y los dedos después del rescate, especialmente tras contacto con vidrio, lámina o fluidos, y retira el guante si el material está cortado.' }] },
  '/guantes/romak-firemax-vi/': { lead: 'El Romak Firemax VI se inspecciona por pares antes de guardia. Revisa que dedos y palma conserven forma, que las costuras no estén abiertas y que el puño solape con la manga del chaquetón durante las posiciones de trabajo.', faqsExtra: [{ q: '¿Cómo reviso el puño de un Romak Firemax VI?', a: 'Ponte el guante con el chaquetón y levanta brazos, gira muñecas y cierra la mano. El puño debe solapar con la manga sin dejar piel expuesta. Revisa también costuras, palma y dedos, por fuera y por dentro, antes de asignarlo.' }] },
  '/guantes/skold-fpgs/': { lead: 'El Sköld FPGS se revisa después de secarlo por completo. Observa costuras de cada dedo, palma y puño, y conserva la bandola interna solo para el secado previsto. La prueba final se hace con manga y herramienta de servicio.', faqsExtra: [{ q: '¿Qué debo inspeccionar en los dedos de un Sköld FPGS?', a: 'Revisa costuras, forro y tacto interior de cada dedo, además de palma y puño. Busca abrasión, costuras abiertas o rigidez por exposición. Luego pruébalo con la manga del chaquetón y una herramienta para confirmar que conserve movilidad y solape.' }] },
  '/guantes/veridian-fire-pro-ii/': { lead: 'El Veridian Fire Pro II se revisa por la continuidad de palma, dedos, barrera y puño antes de entrar a servicio. Pruébalo con el chaquetón y la boquilla para confirmar destreza, agarre y una interfaz cerrada en la muñeca.', faqsExtra: [{ q: '¿Cómo confirmo la interfaz de un Veridian Fire Pro II?', a: 'Colócalo con el chaquetón, levanta los brazos y gira las muñecas mientras sujetas la boquilla o herramienta. El puño debe permanecer bajo la manga sin huecos. Después revisa palma, dedos y costuras para detectar daño o pérdida de flexibilidad.' }] }
};

for (const [path, complemento] of Object.entries(COMPLEMENTOS_4B1)) {
  const anterior = METAS_SEO[path] ?? {};
  METAS_SEO[path] = {
    ...anterior,
    ...complemento,
    faqsExtra: [...(anterior.faqsExtra ?? []), ...(complemento.faqsExtra ?? [])]
  };
}

// Complementos 4B2: orientación de uso e inspección específica por ficha.
const COMPLEMENTOS_4B2: Record<string, Partial<MetaSeo>> = {
  '/rescate/mosquetones-de-rescate/': { lead: 'Los mosquetones de rescate son conectores de seguridad para unir cuerda, anclaje y sistema durante trabajos en altura. Antes de usarlos, revisa cuerpo, gatillo, bloqueo y marcas de identificación. Elige el tipo de mosquetón con base en la cuerda, el conector y la maniobra de rescate, no para escalada recreativa sin el procedimiento correspondiente.', faqsExtra: [{ q: '¿Qué reviso en un mosquetón de rescate antes de una maniobra?', a: 'Revisa que el gatillo cierre por completo, que el bloqueo funcione y que no haya golpes, bordes ásperos, corrosión o deformación. Mantén el mosquetón limpio y seco. Si recibió una carga anormal o presenta daño, retíralo del equipo y sigue el procedimiento de inspección de tu corporación.' }] },
  '/mangueras-y-accesorios/piton-boquilla/': { lead: 'El pitón o chiflón para manguera contra incendio permite controlar el agua como chorro directo o neblina, según la configuración del modelo. Al recibir la boquilla, coteja diámetro, tipo de conexión y cierre con la línea disponible. Prueba el patrón de agua con guante, porque el control depende de la compatibilidad entre manguera, acople y boquilla.', faqsExtra: [{ q: '¿Cómo reviso un chiflón antes de conectarlo a la manguera?', a: 'Confirma que la conexión esté limpia, que la junta esté completa y que el cierre opere sin atorarse. Después realiza una prueba controlada para identificar el patrón de chorro y neblina. No fuerces una rosca distinta ni uses una conexión improvisada, porque una fuga afecta el control del agua.' }] },
  '/mangueras-y-accesorios/llave-para-hidrante/': { lead: 'La llave para hidrante abre o cierra la tuerca de operación del hidrante y acompaña el abastecimiento de una manguera contra incendio. Antes de asignarla, confirma que el dado corresponda al hidrante de tu zona. Mantén la herramienta limpia y revisa que el mango permita aplicar control sin sustituir la llave spanner de conexiones.', faqsExtra: [{ q: '¿La llave para hidrante sirve para apretar conexiones de manguera?', a: 'No es la misma función. La llave para hidrante actúa sobre la operación del hidrante, mientras la llave spanner trabaja los acoples de la manguera contra incendio. Lleva ambas herramientas cuando la maniobra lo requiera y valida la compatibilidad con las conexiones existentes.' }] },
  '/kits/kit-brigadista/': { lead: 'El kit brigadista reúne equipo de protección para tareas autorizadas de primera respuesta, no un traje de bombero estructural por defecto. Define casco, guante, botas, traje y extintor a partir del análisis de riesgo de la brigada. Al recibir el equipo completo, prueba ajuste, movilidad y compatibilidad antes de asignarlo para una emergencia.', faqsExtra: [{ q: '¿Qué se debe comprobar al recibir un kit brigadista?', a: 'Coteja cada pieza con la orden y prueba el conjunto completo: casco, traje, guantes, botas y los accesorios previstos. Confirma que el equipo corresponda a la tarea autorizada por la brigada. NOM-002-STPS-2010 orienta la organización de brigadas, pero no sustituye el análisis de riesgo.' }] },
  '/accesorios/camara-termica/': { lead: 'La cámara térmica es un accesorio de protección para bombero que muestra contrastes térmicos y apoya búsqueda, rescate e intervención. No reemplaza la valoración de la escena ni el equipo de protección, como casco, guante y traje. Antes de guardia, revisa lente, pantalla, batería, controles y correa, luego practica la lectura de la imagen con tu procedimiento.', faqsExtra: [{ q: '¿Qué inspección previa requiere una cámara térmica para bombero?', a: 'Enciéndela y revisa lente, pantalla, batería, botones y correa antes de entrar a servicio. Confirma que la imagen responda y que el usuario pueda operarla con guante. La cámara térmica apoya la orientación en incendio y rescate, pero sus contrastes no identifican por sí solos todos los peligros.' }] },
  '/accesorios/dispositivo-pass/': { lead: 'El dispositivo PASS es un accesorio de protección para bombero que emite una alarma ante inmovilidad o activación manual. Se integra al casco, traje y equipo de respiración cuando el procedimiento de emergencia lo contempla. Antes de cada turno, revisa energía, alarma audible, sujeción y activación con guante; después confirma que el equipo conozca la respuesta prevista.', faqsExtra: [{ q: '¿Qué prueba diaria necesita un dispositivo PASS?', a: 'Comprueba encendido, activación, señal audible y estado de la energía conforme a su manual. Pruébalo con el traje y guante que usará el bombero para confirmar acceso al control. Un PASS no reemplaza el sistema de compañero, la comunicación ni el procedimiento de rescate de emergencia.' }] },
  '/accesorios/ess-striketeam-xto/': { lead: 'Los ESS Striketeam XTO son goggles para protección ocular en trabajo forestal y rescate, con casco y guante como parte del equipo de protección. Antes de asignarlos, revisa lente, espuma, ventilación, correa y Speed-Clip. Pruébalos con casco, respirador o cubrebocas previsto para confirmar que no cambien el ajuste ni limiten la visión.', faqsExtra: [{ q: '¿Cómo cuido los goggles ESS Striketeam XTO después de una salida?', a: 'Retira polvo y ceniza con el método indicado por el fabricante, sin tallar partículas sobre el lente. Revisa el marco, la correa, la espuma y los clips antes de guardarlos. Sustituye el lente si presenta rayas profundas, grietas o pérdida de visibilidad para la maniobra.' }] },
  '/accesorios/goggles/': { lead: 'Los goggles forman parte del equipo de protección para bomberos cuando ceniza, polvo o escombro amenazan los ojos durante rescate o incendio forestal. Deben combinarse con casco, guante y la protección respiratoria prevista. Revisa lente, marco, ventilación y correa antes de uso. La prueba útil se hace moviendo la cabeza con el casco puesto.', faqsExtra: [{ q: '¿Qué confirma la prueba de goggles con casco de bombero?', a: 'Confirma que la correa mantenga los goggles en su posición, que el casco no los empuje y que la visión permanezca despejada al agacharte. Revisa también que no interfieran con la protección respiratoria prevista. Limpia el lente después del servicio para detectar rayas o grietas.' }] },
  '/accesorios/lampara-de-casco/': { lead: 'La lámpara de casco deja las manos libres mientras el bombero usa herramienta, radio o pasamanos durante una emergencia. Se monta en el casco y se prueba con guante, visor y traje para confirmar que el haz no quede bloqueado. Revisa clip, lente, interruptor y batería antes de cada guardia. Complementa la linterna portátil cuando necesitas apuntar la luz fuera de tu mirada.', faqsExtra: [{ q: '¿Qué debo probar al montar una lámpara de casco?', a: 'Prueba el clip sobre el casco real, con visor y protección respiratoria si aplica. Enciéndela con guante, gira la cabeza y confirma que el haz ilumine sin reflejarse en el ala. Revisa el sistema de energía y conserva baterías o cargador conforme al modelo.' }] },
  '/accesorios/linterna-de-bombero/': { lead: 'La linterna de bombero dirige luz hacia una conexión, una manguera, un escalón o un punto de rescate que no coincide con la mirada. Es parte del equipo de protección operativo junto con casco, guante y traje. Antes de servicio, revisa lente, interruptor, energía y funda. Ensaya sacarla y guardarla con guantes para evitar perder control de la herramienta.', faqsExtra: [{ q: '¿Qué diferencia hay entre linterna de bombero y lámpara de casco?', a: 'La lámpara de casco ilumina hacia donde mira el usuario y deja ambas manos libres. La linterna se apunta de forma independiente para revisar una manguera, una puerta o un área de rescate. Ambas requieren prueba con guante, energía disponible y un sistema de porte que no estorbe.' }] },
  '/accesorios/maleta-porta-equipo/': { lead: 'La maleta porta-equipo concentra casco de bomberos, guante, botas, traje y accesorios para trasladarlos sin mezclar piezas sucias con otras limpias. Antes de asignarla, carga el conjunto real y revisa cierres, asas, costuras y base. El material resistente de una maleta no sustituye la limpieza ni el secado del equipo después de una intervención.', faqsExtra: [{ q: '¿Qué debo revisar en una maleta porta-equipo de bombero?', a: 'Revisa costuras, cierres, asas, ruedas si aplica y la base que soporta la carga. Después carga casco, botas, traje y guantes para confirmar que el cierre no fuerce el contenido. Limpia el interior conforme al material y evita guardar equipo contaminado con artículos limpios.' }] },
  '/accesorios/romak-bps1005/': { lead: 'La Romak Fire BPS1005 es una maleta porta-equipo para transportar casco de bomberos, guante, traje, botas y accesorios de una asignación. Al recibirla, coteja el código y revisa cierres, asas, costuras y superficie exterior. Carga el conjunto de protección real para confirmar distribución y que la maleta no comprima piezas que deban secarse antes de guardarse.', faqsExtra: [{ q: '¿Cómo organizo el equipo dentro de una Romak Fire BPS1005?', a: 'Coloca las piezas limpias y secas de modo que el casco no aplaste el lente, visor o accesorios. Separa el guante y la ropa de protección de artículos contaminados. Antes de cerrar, revisa que las asas y el cierre trabajen sin tensión excesiva y que puedas identificar el conjunto asignado.' }] },
  '/accesorios/streamlight-vantage/': { lead: 'La Streamlight Vantage es una lámpara de casco que apoya la iluminación con manos libres durante incendio, rescate y otras maniobras de bombero. Confirma que el clip se adapte al casco de bomberos y no interfiera con visor, guante ni traje. Antes de guardia, revisa lente, interruptor, giro del cabezal y baterías. Llévala junto con una linterna cuando la operación exija luz dirigida.', faqsExtra: [{ q: '¿Qué reviso en una Streamlight Vantage antes de asignarla?', a: 'Monta la lámpara en el casco previsto y comprueba el clip, el giro del cabezal, el interruptor y el estado de la energía. Pruébala con visor y guantes para detectar interferencias. Después de exposición a humo o agua, limpia lente y carcasa según las indicaciones del fabricante.' }] },
  '/herramientas/batefuego/': { lead: 'El batefuego es una herramienta de bombero forestal para sofocar llama baja en pasto y hojarasca sin levantar combustible encendido. Se usa con casco, guante y el resto del equipo de la brigada. Antes de salir, revisa paleta, uniones y mango. Mantén el agarre firme y aplica golpes controlados desde el borde del incendio, según la técnica de la brigada.', faqsExtra: [{ q: '¿Cómo se inspecciona un batefuego antes de una salida forestal?', a: 'Revisa que la paleta flexible no tenga cortes, separación o deformación y que el mango permanezca firme. Limpia tierra y vegetación después de uso para revisar el estado de la herramienta. Si el mango está flojo o la paleta dañada, aparta el batefuego hasta corregirlo.' }] },
  '/herramientas/bomba-de-mochila-forestal/': { lead: 'La bomba de mochila forestal es una herramienta portátil para llevar agua y aplicar un chorro localizado sobre brasas o llama baja. El bombero la usa con casco, guante y equipo de brigada durante una emergencia forestal. Antes de cargarla, revisa depósito, tapa, manguera, boquilla, correas y bombeo. Limpia el sistema después de uso para evitar obstrucciones.', faqsExtra: [{ q: '¿Qué prueba hago a una bomba de mochila forestal antes de despliegue?', a: 'Llénala conforme al procedimiento y comprueba que no existan fugas en depósito, tapa, manguera o boquilla. Acciona la bomba y confirma un chorro controlable antes de salir. Ajusta las correas con el equipo puesto para que la herramienta permanezca estable al caminar en terreno irregular.' }] },
  '/herramientas/gancho-bichero/': { lead: 'El gancho bichero es una herramienta de bombero para alcanzar, jalar y abrir material desde una posición controlada durante un incendio o rescate. Revisa gancho, punta, mango y uniones antes de guardia. Úsalo con casco, guante y la distancia que permita la técnica autorizada. No lo uses como palanca si la maniobra requiere otra herramienta de entrada.', faqsExtra: [{ q: '¿Qué partes debo inspeccionar en un gancho bichero?', a: 'Inspecciona el gancho y la punta por deformación, el mango por grietas y las uniones por juego. Limpia residuos después de cada uso para detectar daño. La herramienta debe conservar un agarre seguro y resguardarse de modo que su punta no pueda lesionar al personal durante el traslado.' }] },
  '/herramientas/romak-hac1007/': { lead: 'La Romak Fire HAC1007 es una herramienta Halligan para maniobras autorizadas de entrada forzada y rescate. Antes de asignarla, revisa horquilla, cuña, pico y superficie de agarre. El bombero debe usar casco y guante, y llevarla con un resguardo que proteja sus puntas. No sustituye hacha, gancho ni capacitación de la brigada para acceso controlado.', faqsExtra: [{ q: '¿Cómo reviso una Romak Fire HAC1007 antes de entrar a servicio?', a: 'Busca deformación, grietas, corrosión o bordes dañados en la horquilla, cuña y pico. Comprueba que el resguardo previsto mantenga cubiertas las puntas durante el traslado. Limpia la herramienta después de la maniobra y retírala si sufrió una deformación que cambie su funcionamiento.' }] },
  '/kits/kit-estructural/': { lead: 'El kit estructural reúne traje de bombero, casco, guante, botas y capucha para una configuración de equipo completo definida por el riesgo. No basta con que cada pieza exista: prueba el conjunto con respiración autónoma, movilidad y cierre de interfaces. Al recibirlo, coteja la orden, revisa protección térmica y confirma que la certificación declarada corresponda a cada componente.', faqsExtra: [{ q: '¿Cómo se prueba un kit estructural antes de asignarlo?', a: 'Pruébalo como conjunto: traje, casco, capucha, guantes, botas y el equipo de respiración autónoma previsto. Levanta brazos, agáchate y mueve la cabeza para identificar huecos o interferencias. Revisa la información de certificación que declare cada fabricante y conserva las fichas de los componentes.' }] },
  '/kits/kit-forestal/': { lead: 'El kit forestal reúne traje, casco, guante, botas y goggles para que el bombero trabaje en línea de fuego con una configuración completa. La selección parte de la brigada, el terreno y la tarea autorizada, no de un equipo estructural. Al recibirlo, revisa ajuste, protección térmica, movilidad y cuidado de cada pieza; confirma la certificación que declare su fabricante cuando aplique.', faqsExtra: [{ q: '¿Qué diferencia al kit forestal de un kit estructural?', a: 'El kit forestal se configura para trabajo prolongado en línea de fuego, terreno irregular y herramienta manual. El estructural responde a otra exposición y otra interfaz de traje, casco y respiración autónoma. Prueba cada conjunto con su maniobra, y no intercambies piezas sin revisar su uso previsto y la información declarada.' }] },
  '/mangueras-y-accesorios/conexiones-y-adaptadores/': { lead: 'Las conexiones y adaptadores unen una manguera contra incendio con hidrante, boquilla, tubo o equipo de otra rosca. Antes de instalarlos, identifica diámetro, tipo de conexión, material y presión de trabajo declarada. Revisa juntas, roscas y caras de acople limpias. Una adaptación compatible conserva el control del agua; una improvisada puede causar fuga o dañar la conexión.', faqsExtra: [{ q: '¿Qué debo comprobar antes de usar un adaptador para manguera contra incendio?', a: 'Comprueba diámetro, tipo de rosca o acople, juntas y la compatibilidad entre la manguera, hidrante y boquilla. Revisa que no haya golpes, roscas barridas ni suciedad. Haz una prueba controlada de conexión antes de usarla en una emergencia y conserva la identificación de cada adaptador.' }] }
};

for (const [path, complemento] of Object.entries(COMPLEMENTOS_4B2)) {
  const anterior = METAS_SEO[path] ?? {};
  METAS_SEO[path] = {
    ...anterior,
    ...complemento,
    faqsExtra: [...(anterior.faqsExtra ?? []), ...(complemento.faqsExtra ?? [])]
  };
}
